workflows:
  ios-complete:
    name: iOS Complete Build
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: Setup fastlane
        script: |
          # 安装 fastlane
          sudo gem install fastlane -NV
          
          # 创建必要的 fastlane 配置
          mkdir -p fastlane
          
          # 创建 Appfile
          cat > fastlane/Appfile << EOF
          app_identifier "com.test.ios.attaf"
          apple_id "lingya00130@gmail.com"
          team_id "7994453ZHZ"
          EOF
          
          # 创建 Fastfile
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            desc "Build iOS app for App Store"
            lane :release do
              # 设置版本号（可选）
              # increment_build_number
              
              # 构建应用
              gym(
                workspace: "123.xcworkspace",
                scheme: "123",
                configuration: "Release",
                output_directory: "build",
                export_method: "app-store",
                export_options: {
                  method: "app-store",
                  teamID: "7994453ZHZ",
                  uploadBitcode: false,
                  compileBitcode: false
                },
                silent: false,
                clean: true
              )
              
              # 可选：上传到 TestFlight
              # pilot
            end
          end
          EOF
          
          echo "Fastlane configuration created"
      
      - name: Run fastlane build
        script: |
          cd fastlane
          
          # 运行 fastlane
          fastlane ios release
          
          # 回到项目根目录
          cd ..
      
      - name: Collect artifacts
        script: |
          echo "Build artifacts:"
          find . -name "*.ipa" -type f | xargs ls -lh
          
          # 确保 IPA 在 build 目录
          if ls build/*.ipa 1> /dev/null 2>&1; then
            echo "✅ IPA found in build directory"
          else
            # 查找 IPA 文件
            IPA_FILE=$(find . -name "*.ipa" -type f | head -1)
            if [ -n "$IPA_FILE" ]; then
              echo "Found IPA at: $IPA_FILE"
              mkdir -p build
              cp "$IPA_FILE" build/
            fi
          fi
    
    artifacts:
      - build/*.ipa
      - fastlane/logs/*.log
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
