workflows:
  ios-fastlane:
    name: iOS with Fastlane
    environment:
      xcode: latest
      groups:
        - appstore_signing
      vars:
        FASTLANE_USER: "lingya00130@gmail.com"  # 您的 Apple ID
    
    scripts:
      - name: Install fastlane
        script: |
          sudo gem install fastlane -NV
      
      - name: Build with fastlane gym
        script: |
          # 使用 fastlane 处理所有签名细节
          fastlane run build_ios_app \
            workspace: "123.xcworkspace" \
            scheme: "123" \
            clean: true \
            output_directory: "build" \
            export_method: "app-store" \
            silent: true \
            skip_package_ipa: false
      
      - name: Verify build
        script: |
          if ls build/*.ipa 1> /dev/null 2>&1; then
            echo "✅ Build successful!"
            ls -lh build/*.ipa
          else
            echo "❌ Build failed"
            exit 1
          fi
