workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
        
        # 代码签名配置
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_NAME: "codemagic_Production"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    
    scripts:
      # 1. 设置环境和显示项目配置
      - name: Setup environment
        script: |
          echo "=== 设置环境 ==="
          echo "当前目录: $(pwd)"
          echo "Scheme: $XCODE_SCHEME"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $APP_IDENTIFIER"
          echo "代码签名身份: $CODE_SIGN_IDENTITY"
          echo "配置文件: $PROVISIONING_PROFILE_NAME"
          
          # 显示项目结构
          echo "项目结构:"
          ls -la
          
          # 显示项目文件内容
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "项目文件大小: $(wc -l < 123.xcodeproj/project.pbxproj) 行"
            echo "检查项目配置中的签名设置:"
            grep -n -A 2 -B 2 "DEVELOPMENT_TEAM\|CODE_SIGN\|PROVISIONING" 123.xcodeproj/project.pbxproj | head -50 || echo "未找到相关设置"
          fi
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 使用Python脚本修复项目文件（更可靠的方法）
      - name: Fix project configuration with Python
        script: |
          echo "=== 使用Python修复项目配置 ==="
          
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "备份项目文件..."
            cp 123.xcodeproj/project.pbxproj 123.xcodeproj/project.pbxproj.backup
            
            # 创建Python脚本来修复项目文件
            cat > fix_project.py << EOF
          #!/usr/bin/env python3
          import re
          import sys
          
          # 读取项目文件
          with open('123.xcodeproj/project.pbxproj', 'r') as f:
              content = f.read()
          
          print("原始文件大小:", len(content), "字符")
          
          # 1. 确保有DEVELOPMENT_TEAM设置
          if 'DEVELOPMENT_TEAM = ' not in content:
              print("添加DEVELOPMENT_TEAM设置...")
              # 在适当的位置添加DEVELOPMENT_TEAM
              content = re.sub(
                  r'(\s+attributes = \{[\s\S]*?)(\s+\};)',
                  lambda m: m.group(1) + f'\n\t\t\tDEVELOPMENT_TEAM = {sys.argv[1]};' + m.group(2),
                  content
              )
          else:
              print("更新DEVELOPMENT_TEAM设置...")
              content = re.sub(
                  r'DEVELOPMENT_TEAM = [^;]+;',
                  f'DEVELOPMENT_TEAM = {sys.argv[1]};',
                  content
              )
          
          # 2. 确保有PRODUCT_BUNDLE_IDENTIFIER设置
          if 'PRODUCT_BUNDLE_IDENTIFIER = ' not in content:
              print("添加PRODUCT_BUNDLE_IDENTIFIER设置...")
              # 在Build Settings中添加
              content = re.sub(
                  r'(\s+buildSettings = \{[\s\S]*?)(\s+\};)',
                  lambda m: m.group(1) + f'\n\t\t\tPRODUCT_BUNDLE_IDENTIFIER = {sys.argv[2]};' + m.group(2),
                  content,
                  count=1
              )
          else:
              print("更新PRODUCT_BUNDLE_IDENTIFIER设置...")
              content = re.sub(
                  r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;',
                  f'PRODUCT_BUNDLE_IDENTIFIER = {sys.argv[2]};',
                  content
              )
          
          # 3. 设置CODE_SIGN_STYLE为Manual
          if 'CODE_SIGN_STYLE = ' not in content:
              print("添加CODE_SIGN_STYLE设置...")
              content = re.sub(
                  r'(\s+buildSettings = \{[\s\S]*?)(\s+\};)',
                  lambda m: m.group(1) + f'\n\t\t\tCODE_SIGN_STYLE = Manual;' + m.group(2),
                  content,
                  count=1
              )
          else:
              print("更新CODE_SIGN_STYLE为Manual...")
              content = re.sub(
                  r'CODE_SIGN_STYLE = [^;]+;',
                  'CODE_SIGN_STYLE = Manual;',
                  content
              )
          
          # 4. 设置CODE_SIGN_IDENTITY
          print("设置CODE_SIGN_IDENTITY...")
          content = re.sub(
              r'CODE_SIGN_IDENTITY = [^;]+;',
              f'CODE_SIGN_IDENTITY = {sys.argv[3]};',
              content
          )
          if 'CODE_SIGN_IDENTITY = ' not in content:
              content = re.sub(
                  r'(\s+buildSettings = \{[\s\S]*?)(\s+\};)',
                  lambda m: m.group(1) + f'\n\t\t\tCODE_SIGN_IDENTITY = {sys.argv[3]};' + m.group(2),
                  content,
                  count=1
              )
          
          # 5. 设置PROVISIONING_PROFILE_SPECIFIER
          print("设置PROVISIONING_PROFILE_SPECIFIER...")
          content = re.sub(
              r'PROVISIONING_PROFILE_SPECIFIER = [^;]+;',
              f'PROVISIONING_PROFILE_SPECIFIER = {sys.argv[4]};',
              content
          )
          if 'PROVISIONING_PROFILE_SPECIFIER = ' not in content:
              content = re.sub(
                  r'(\s+buildSettings = \{[\s\S]*?)(\s+\};)',
                  lambda m: m.group(1) + f'\n\t\t\tPROVISIONING_PROFILE_SPECIFIER = {sys.argv[4]};' + m.group(2),
                  content,
                  count=1
              )
          
          # 写入修复后的文件
          with open('123.xcodeproj/project.pbxproj', 'w') as f:
              f.write(content)
          
          print("✅ 项目文件修复完成")
          print("修复后的文件大小:", len(content), "字符")
          EOF
            
            # 运行Python脚本修复项目文件
            python3 fix_project.py "$TEAM_ID" "$APP_IDENTIFIER" "$CODE_SIGN_IDENTITY" "$PROVISIONING_PROFILE_NAME"
            
            echo "验证修复结果:"
            echo "DEVELOPMENT_TEAM:"
            grep -n "DEVELOPMENT_TEAM = " 123.xcodeproj/project.pbxproj || echo "未找到"
            echo "PRODUCT_BUNDLE_IDENTIFIER:"
            grep -n "PRODUCT_BUNDLE_IDENTIFIER = " 123.xcodeproj/project.pbxproj || echo "未找到"
            echo "CODE_SIGN_STYLE:"
            grep -n "CODE_SIGN_STYLE = " 123.xcodeproj/project.pbxproj || echo "未找到"
            echo "CODE_SIGN_IDENTITY:"
            grep -n "CODE_SIGN_IDENTITY = " 123.xcodeproj/project.pbxproj || echo "未找到"
            echo "PROVISIONING_PROFILE_SPECIFIER:"
            grep -n "PROVISIONING_PROFILE_SPECIFIER = " 123.xcodeproj/project.pbxproj || echo "未找到"
          else
            echo "❌ 未找到项目配置文件"
          fi
      
      # 3. 构建archive（使用修复后的配置）
      - name: Build archive with fixed configuration
        script: |
          echo "=== 构建archive（使用修复后的配置）==="
          
          # 清理之前的构建
          rm -rf build/*.xcarchive
          
          # 使用Codemagic代码签名工具
          echo "应用Codemagic代码签名配置..."
          xcode-project use-profiles 2>&1 | head -20 || echo "xcode-project use-profiles 执行完成"
          
          # 构建archive，使用项目文件中的配置
          echo "构建archive..."
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace构建..."
            
            xcodebuild archive \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              2>&1 | tee build/archive.log
            
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project构建..."
            
            xcodebuild archive \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              2>&1 | tee build/archive.log
          fi
          
          # 检查archive是否成功
          if [ -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "✅ archive构建成功"
            
            # 显示archive中的app签名信息
            echo "检查archive中的签名..."
            APP_PATH="build/$XCODE_SCHEME.xcarchive/Products/Applications/$XCODE_SCHEME.app"
            if [ -d "$APP_PATH" ]; then
              echo "应用签名信息:"
              codesign -d -vvv "$APP_PATH" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier" || echo "无法获取签名详情"
            else
              echo "⚠️ 未找到.app文件"
              echo "Archive内容:"
              find "build/$XCODE_SCHEME.xcarchive" -type f -name "*.app" 2>/dev/null || echo "无.app文件"
            fi
          else
            echo "❌ archive构建失败"
            echo "查看日志最后100行:"
            tail -100 build/archive.log
            exit 1
          fi
      
      # 4. 导出IPA
      - name: Export IPA
        script: |
          echo "=== 导出IPA ==="
          
          # 清理之前的IPA
          rm -rf build/*.ipa
          
          # 创建export_options.plist
          cat > build/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_IDENTIFIER</key>
                  <string>$PROVISIONING_PROFILE_NAME</string>
              </dict>
              <key>signingCertificate</key>
              <string>$CODE_SIGN_IDENTITY</string>
          </dict>
          </plist>
          EOF
          
          echo "export_options.plist内容:"
          cat build/export_options.plist
          
          # 执行导出
          echo "开始导出IPA..."
          xcodebuild -exportArchive \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist "build/export_options.plist" \
            -exportPath "build" \
            -allowProvisioningUpdates \
            2>&1 | tee build/export.log
          
          echo "✅ 导出完成"
      
      # 5. 验证和重命名IPA文件
      - name: Verify and rename IPA
        script: |
          echo "=== 验证和重命名IPA文件 ==="
          
          # 查找生成的IPA文件
          echo "查找IPA文件..."
          IPA_FILES=$(find build -name "*.ipa" 2>/dev/null)
          
          if [ -z "$IPA_FILES" ]; then
            echo "❌ 未找到IPA文件"
            echo "导出日志最后100行:"
            tail -100 build/export.log || echo "无导出日志"
            exit 1
          fi
          
          echo "找到的IPA文件:"
          echo "$IPA_FILES"
          
          # 如果IPA文件不在根目录，移动到根目录
          if [ ! -f "build/$XCODE_SCHEME.ipa" ]; then
            FIRST_IPA=$(echo "$IPA_FILES" | head -1)
            echo "将IPA文件复制到标准位置: $FIRST_IPA -> build/$XCODE_SCHEME.ipa"
            cp "$FIRST_IPA" "build/$XCODE_SCHEME.ipa"
          fi
          
          # 验证IPA文件
          if [ -f "build/$XCODE_SCHEME.ipa" ]; then
            echo "✅ IPA文件创建成功: build/$XCODE_SCHEME.ipa"
            echo "文件大小: $(du -h "build/$XCODE_SCHEME.ipa" | cut -f1)"
            
            # 验证签名
            echo "验证IPA签名..."
            codesign -d -vvv "build/$XCODE_SCHEME.ipa" 2>&1 | head -20 || echo "无法验证IPA签名"
          else
            echo "❌ IPA文件未创建"
            exit 1
          fi
      
      # 6. 显示构建摘要
      - name: Build summary
        script: |
          echo "=== 构建摘要 ==="
          echo "✅ 构建成功!"
          echo ""
          echo "生成的产物:"
          echo "IPA: build/$XCODE_SCHEME.ipa"
          echo "Archive: build/$XCODE_SCHEME.xcarchive"
          echo ""
          echo "文件大小:"
          du -h "build/$XCODE_SCHEME.ipa" 2>/dev/null || echo "IPA文件不存在"
          du -h "build/$XCODE_SCHEME.xcarchive" 2>/dev/null || echo "Archive不存在"
          echo ""
          echo "构建完成时间: $(date)"
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - build/export_options.plist
      - build/archive.log
      - build/export.log
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "717@stlnd.net"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
