workflows:
  ios-test:
    name: iOS Test Build
    environment:
      xcode: latest
    
    scripts:
      - name: Test project structure
        script: |
          echo "=== Testing project structure ==="
          
          # 检查文件
          pwd
          ls -la
          
          # 检查是否能列出 schemes
          echo "Listing schemes:"
          xcodebuild -workspace "123.xcworkspace" -list 2>&1 || echo "Cannot list schemes"
          
          # 尝试简单的构建（不签名）
          echo "Testing build without signing:"
          xcodebuild build \
            -workspace "123.xcworkspace" \
            -scheme "123" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO 2>&1 | tail -20 || echo "Build test completed"
          
          echo "✅ Project structure seems OK"
      
      - name: Test archive without signing
        script: |
          echo "=== Testing archive without signing ==="
          
          # 尝试归档但不签名
          xcodebuild archive \
            -workspace "123.xcworkspace" \
            -scheme "123" \
            -configuration Debug \
            -archivePath "build/test.xcarchive" \
            CODE_SIGNING_ALLOWED=NO 2>&1 | tail -20 || echo "Archive test completed"
          
          if [ -d "build/test.xcarchive" ]; then
            echo "✅ Archive created (without signing)"
          else
            echo "❌ Archive failed"
          fi
