workflows:
  ios-simple:
    name: iOS Simple Build
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: Install profile and build
        script: |
          # 1. 安装描述文件
          curl -L -o profile.mobileprovision "$APPSTORE_PROVISIONING_PROFILE_URL"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # 2. 使用 fastlane 构建
          sudo gem install fastlane -NV
          
          cat > Fastfile << 'EOF'
          lane :build do
            gym(
              workspace: "123.xcworkspace",
              scheme: "123",
              export_method: "app-store",
              output_directory: "build"
            )
          end
          EOF
          
          fastlane build
      
      - name: Check result
        script: |
          if [ -f "build/*.ipa" ]; then
            echo "Build successful"
          else
            echo "Checking for IPA..."
            find . -name "*.ipa" -type f
          fi
    
    artifacts:
      - build/*.ipa
