workflows:
  ios-minimal:
    name: iOS Minimal
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
        XCODE_SCHEME: "123"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    
    scripts:
      - name: 安装依赖
        script: |
          # 如果有Podfile就安装
          [ -f "Podfile" ] && pod install || echo "没有Podfile"
      
      - name: 构建
        script: |
          echo "构建IPA..."
          
          # 最简单的命令
          xcode-project build-ipa \
            --workspace "123.xcworkspace" \
            --scheme "$XCODE_SCHEME"
          
          echo "构建完成!"
          
          # 显示当前目录结构
          echo "当前目录结构:"
          find . -name "*.ipa" -o -name "*.xcarchive" | head -20
    
    # 收集所有可能的IPA文件
    artifacts:
      - "**/*.ipa"
      - "build/ios/ipa/*"
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
