workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_signing  # 包含证书和配置文件的组
        - appstore_connect  # App Store Connect API 密钥组
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"  # 你的团队ID，从证书中获取
        SCHEME: "123"  # 你的Xcode scheme名称
        
        # Xcode 项目配置（根据实际情况调整）
        XCODE_WORKSPACE: "123.xcworkspace"  # 或者使用 XCODE_PROJECT
        XCODE_SCHEME: "123"
        
        # 版本管理（可选）
        BUILD_NUMBER: "$(date +%Y%m%d%H%M)"
        
        # 代码签名配置 - 从Codmagenic UI获取
        CODE_SIGNING_IDENTITY: "Apple Distribution: Ya ling Hsu"
        PROVISIONING_PROFILE_NAME: "codemagic_Production"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
        - pattern: 'test/beta'
          include: true
      cancel_previous_builds: false
    
    cache:
      paths:
        - vendor/bundle
        - fastlane/logs
        - Pods
        - DerivedData
    
    scripts:
      # 1. 安装和设置fastlane
      - name: Setup build environment
        script: |
          echo "=== 设置构建环境 ==="
          echo "应用标识符: $APP_IDENTIFIER"
          echo "团队ID: $TEAM_ID"
          echo "Xcode scheme: $XCODE_SCHEME"
          echo "代码签名身份: $CODE_SIGNING_IDENTITY"
          echo "配置文件: $PROVISIONING_PROFILE_NAME"
          
          # 安装fastlane
          sudo gem install fastlane -NV
          
          # 确保必要的目录存在
          mkdir -p fastlane
          mkdir -p build
    
      # 2. 准备代码签名
      - name: Prepare code signing
        script: |
          echo "=== 准备代码签名 ==="
          
          # 列出可用的证书
          echo "可用的证书:"
          security find-identity -p codesigning -v
          
          # 列出配置文件
          echo "已安装的配置文件:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ | head -10
          
          # 检查特定证书是否存在
          if security find-identity -p codesigning -v | grep -q "Ya ling Hsu"; then
            echo "✅ 找到证书: Ya ling Hsu"
          else
            echo "❌ 未找到证书: Ya ling Hsu"
            exit 1
          fi
    
      # 3. 创建fastlane配置文件
      - name: Configure fastlane
        script: |
          echo "=== 配置fastlane ==="
          
          # 1. 创建Appfile
          cat > fastlane/Appfile << EOF
          # 应用标识符
          app_identifier "$APP_IDENTIFIER"
          
          # Apple ID
          apple_id "$APPLE_ID"
          
          # 团队ID
          team_id "$TEAM_ID"
          
          # 可选的iTunes Connect团队
          itc_team_id "$TEAM_ID"
          EOF
          
          # 2. 创建Fastfile
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            desc "发布到App Store"
            lane :release do |options|
              # 设置版本号（可选）
              if ENV['BUILD_NUMBER']
                increment_build_number(
                  build_number: ENV['BUILD_NUMBER']
                )
              end
              
              # 构建应用
              gym(
                # Xcode项目配置
                workspace: "$XCODE_WORKSPACE",
                scheme: "$XCODE_SCHEME",
                configuration: "Release",
                
                # 输出配置
                output_directory: "./build",
                output_name: "$XCODE_SCHEME.ipa",
                export_method: "app-store",
                
                # 代码签名配置
                codesigning_identity: "$CODE_SIGNING_IDENTITY",
                export_options: {
                  provisioningProfiles: {
                    "$APP_IDENTIFIER" => "$PROVISIONING_PROFILE_NAME"
                  },
                  signingCertificate: "$CODE_SIGNING_IDENTITY",
                  teamID: "$TEAM_ID"
                },
                
                # 其他选项
                clean: true,
                silent: false,
                skip_package_ipa: false,
                include_symbols: true,
                include_bitcode: false,
                build_path: "./build"
              )
              
              # 验证构建
              verify_build(
                app_identifier: "$APP_IDENTIFIER",
                ipa_path: "./build/$XCODE_SCHEME.ipa"
              )
            end
            
            # 测试构建
            lane :beta do
              gym(
                workspace: "$XCODE_WORKSPACE",
                scheme: "$XCODE_SCHEME",
                configuration: "Release",
                export_method: "app-store",
                output_directory: "./build",
                output_name: "$XCODE_SCHEME.ipa"
              )
            end
            
            # 仅构建（不上传）
            lane :build_only do
              gym(
                workspace: "$XCODE_WORKSPACE",
                scheme: "$XCODE_SCHEME",
                configuration: "Release",
                export_method: "app-store",
                output_directory: "./build",
                output_name: "$XCODE_SCHEME.ipa",
                skip_package_ipa: false
              )
            end
          end
          EOF
          
          echo "✅ Fastlane配置创建完成"
    
      # 4. 使用fastlane构建
      - name: Build with fastlane
        script: |
          echo "=== 开始构建 ==="
          
          # 进入fastlane目录并执行构建
          cd fastlane
          
          # 根据触发分支选择构建类型
          if [[ "$CM_BRANCH" == "main" ]]; then
            echo "执行正式发布构建..."
            fastlane ios release
          elif [[ "$CM_BRANCH" == *"release"* ]]; then
            echo "执行发布分支构建..."
            fastlane ios release
          else
            echo "执行测试构建..."
            fastlane ios beta
          fi
          
          # 返回项目根目录
          cd ..
          
          echo "✅ 构建完成"
    
      # 5. 验证构建产物
      - name: Verify build artifacts
        script: |
          echo "=== 验证构建产物 ==="
          
          # 检查IPA文件
          IPA_PATH="build/$XCODE_SCHEME.ipa"
          
          if [ -f "$IPA_PATH" ]; then
            echo "✅ IPA文件生成成功: $IPA_PATH"
            echo "文件大小: $(du -h "$IPA_PATH" | cut -f1)"
            
            # 显示IPA基本信息
            echo "--- IPA基本信息 ---"
            unzip -l "$IPA_PATH" | grep "Payload/" | head -3
          else
            echo "❌ 未找到IPA文件"
            echo "当前目录内容:"
            ls -la
            echo "build目录内容:"
            ls -la build/ || echo "build目录不存在"
            exit 1
          fi
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - fastlane/Appfile
      - fastlane/Fastfile
      - fastlane/logs/*.log
      - Pods/  # 缓存Pod依赖
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        # 使用环境变量组中的API密钥
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        # 提交到TestFlight
        submit_to_testflight: true
        
        # 自动提交到App Store Review（可选）
        # submit_to_app_store: true
        
        # 应用信息
        app_id: "$APP_IDENTIFIER"
        
        # 发布选项
        release_type: AUTOMATIC  # 或 MANUAL
        # 如果手动发布，设置此项为false
        # automatic_release: false
        
        # 测试组（可选）
        beta_groups:
          - "Internal Testers"
