workflows:
  ios-proven:
    name: iOS Proven Build
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: Use proven fastlane config
        script: |
          echo "=== Using proven fastlane configuration ==="
          
          # 清理
          rm -rf build fastlane 2>/dev/null || true
          
          # 安装 fastlane
          sudo gem install fastlane -NV
          
          # 创建 fastlane 配置（基于之前成功的配置）
          mkdir -p fastlane
          
          # 创建 Fastfile（与之前成功的完全一样）
          cat > fastlane/Fastfile << 'EOF'
          default_platform(:ios)
          
          platform :ios do
            lane :release do
              # 构建 IPA
              gym(
                workspace: "123.xcworkspace",
                scheme: "123",
                configuration: "Release",
                output_directory: "build",
                export_method: "app-store",
                export_options: {
                  method: "app-store",
                  teamID: "7994453ZHZ",
                  uploadBitcode: false,
                  compileBitcode: false
                },
                clean: true,
                silent: false,
                skip_package_ipa: false,
                skip_archive: false,
                include_symbols: true,
                include_bitcode: false
              )
            end
          end
          EOF
          
          # 创建 Appfile
          cat > fastlane/Appfile << EOF
          app_identifier "com.test.ios.attaf"
          apple_id "lingya00130@gmail.com"
          team_id "7994453ZHZ"
          EOF
          
          echo "Configuration files created"
          
          # 运行构建
          cd fastlane
          fastlane ios release
          cd ..
          
          echo "Build completed"
      
      - name: Find and collect IPA
        script: |
          echo "=== Finding IPA file ==="
          
          # 搜索 IPA 文件（包括嵌套目录）
          echo "Searching recursively for IPA files..."
          find . -type f -name "*.ipa" 2>/dev/null | while read ipa; do
            echo "Found IPA: $ipa"
            # 获取文件信息
            echo "  Size: $(du -h "$ipa" | cut -f1)"
            echo "  Location: $(dirname "$ipa")"
          done
          
          # 复制到 build 目录
          mkdir -p build
          IPA_COUNT=0
          find . -type f -name "*.ipa" ! -path "./build/*" 2>/dev/null | while read ipa; do
            IPA_COUNT=$((IPA_COUNT + 1))
            echo "Copying $ipa to build/"
            cp "$ipa" "build/app_$IPA_COUNT.ipa"
          done
          
          if [ $IPA_COUNT -gt 0 ]; then
            echo "✅ Successfully copied $IPA_COUNT IPA files to build directory"
            ls -lh build/
          else
            echo "❌ No IPA files found anywhere"
            
            # 调试：列出 fastlane 输出目录
            echo "Checking fastlane output directories..."
            find . -type d -name "output" -o -name "builds" 2>/dev/null | while read dir; do
              echo "Checking $dir:"
              ls -la "$dir/" 2>/dev/null || echo "  (empty or inaccessible)"
            done
            
            exit 1
          fi
    
    artifacts:
      - build/*.ipa
