workflows:
  appstore-release:
    name: iOS App Store Release
    environment:
      xcode: latest
      groups:
        - appstore_signing  # 生产证书组
      vars:
        BUNDLE_ID: "com.yourcompany.app"  # 替换为您的 Bundle ID
        SCHEME: "YourApp"  # 替换为您的 Scheme
    
    # iOS 自动代码签名配置 - 使用生产证书
    ios:
      signing:
        certificate_url: $APPSTORE_CERTIFICATE_URL
        certificate_password: $APPSTORE_CERTIFICATE_PASSWORD
        provisioning_profile_url: $APPSTORE_PROVISIONING_PROFILE_URL
    
    # 构建脚本
    scripts:
      - name: Build for App Store
        script: |
          # 设置版本号
          if [ ! -z "$BUILD_NUMBER" ]; then
            agvtool new-version -all $BUILD_NUMBER
          fi
          
          # 安装依赖
          pod install --repo-update
          
          # 构建归档
          xcodebuild archive \
            -workspace "YourApp.xcworkspace" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "build/YourApp.xcarchive" \
            -destination 'generic/platform=iOS'
          
          # 导出 IPA
          xcodebuild -exportArchive \
            -archivePath "build/YourApp.xcarchive" \
            -exportPath "build" \
            -exportOptionsPlist "exportOptions.plist"
    
    # 产物
    artifacts:
      - build/*.ipa
      - build/*.dSYM.zip
    
    # 发布到 App Store Connect
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
