workflows:
  ios-minimal:
    name: iOS Minimal Build
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    
    scripts:
      - name: 构建IPA
        script: |
          # 最简单的构建命令
          xcode-project build-ipa \
            --workspace "$(find . -name '*.xcworkspace' -type d | head -1)" \
            --scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[0]')" \
            --export-method "app-store"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
