workflows:
  ios-env-signing:
    name: iOS Environment Signing
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
      
      # 使用环境变量组中的证书
      groups:
        - ios_signing_credentials  # 在Codemagic UI中创建此组
    
    # 不需要在YAML中指定ios_signing，Codemagic会自动使用环境变量组中的证书
    
    scripts:
      - name: 验证签名证书
        script: |
          # 检查证书是否已加载
          security find-identity -v -p codesigning
      
      - name: 安装依赖
        script: |
          if [ -f "Podfile" ]; then
            pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          else
            echo "未找到Podfile，跳过pod install"
          fi
      
      - name: 构建应用
        script: |
          # 构建选项
          xcode-project build-ios \
            --workspace "$(find . -name '*.xcworkspace' -type d | head -1)" \
            --scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[0]')" \
            --output "build/ios" \
            --codesigning "manual" \
            --export-options-plist-config '{"method": "app-store", "uploadBitcode": false}'
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
