workflows:
  ios-diagnostic:
    name: iOS Diagnostic Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "123"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
      cancel_previous_builds: false
    
    scripts:
      # 1. 详细显示项目结构
      - name: Detailed project structure
        script: |
          echo "=== 详细项目结构 ==="
          echo "当前目录: $(pwd)"
          echo ""
          echo "所有文件和目录:"
          find . -maxdepth 2 -type d | sort
          echo ""
          
          # 检查关键文件
          echo "关键文件检查:"
          echo "123.xcworkspace 是否存在: $([ -d "123.xcworkspace" ] && echo "✅ 存在" || echo "❌ 不存在")"
          echo "123.xcodeproj 是否存在: $([ -d "123.xcodeproj" ] && echo "✅ 存在" || echo "❌ 不存在")"
          echo "Podfile 是否存在: $([ -f "Podfile" ] && echo "✅ 存在" || echo "❌ 不存在")"
          
          if [ -d "123.xcworkspace" ]; then
            echo ""
            echo "123.xcworkspace 目录内容:"
            ls -la "123.xcworkspace/"
          fi
          
          if [ -d "123.xcodeproj" ]; then
            echo ""
            echo "123.xcodeproj 目录内容:"
            ls -la "123.xcodeproj/"
          fi
      
      # 2. 检查Xcode项目配置
      - name: Check Xcode project configuration
        script: |
          echo "=== 检查Xcode项目配置 ==="
          
          # 检查project.pbxproj文件
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "✅ 找到项目配置文件"
            
            # 检查target
            echo "检查target配置..."
            grep -n "name = " "123.xcodeproj/project.pbxproj" | grep -i "123" || echo "未找到包含'123'的target"
            
            # 检查product name
            echo "检查产品名称..."
            grep -n "PRODUCT_NAME" "123.xcodeproj/project.pbxproj" | head -10 || echo "未找到PRODUCT_NAME"
            
            # 检查bundle identifier
            echo "检查bundle identifier..."
            grep -n "PRODUCT_BUNDLE_IDENTIFIER" "123.xcodeproj/project.pbxproj" | head -5 || echo "未找到PRODUCT_BUNDLE_IDENTIFIER"
          else
            echo "❌ 未找到项目配置文件"
          fi
      
      # 3. 尝试最简单的构建命令
      - name: Simplest build test
        script: |
          echo "=== 最简单的构建测试 ==="
          
          # 创建一个测试用的build目录
          mkdir -p build_test
          
          # 首先，检查是否可以列出scheme
          echo "1. 检查scheme列表..."
          
          if [ -d "123.xcworkspace" ]; then
            echo "尝试列出workspace的scheme:"
            xcodebuild -list -workspace "123.xcworkspace" 2>&1 || echo "无法列出scheme"
            
            echo ""
            echo "2. 尝试清理项目..."
            xcodebuild clean -workspace "123.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Debug 2>&1 | tail -20 || echo "清理失败"
            
            echo ""
            echo "3. 尝试构建（无签名）..."
            xcodebuild build \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              2>&1 | tee build_test/simple_build.log
              
          elif [ -d "123.xcodeproj" ]; then
            echo "尝试列出project的scheme:"
            xcodebuild -list -project "123.xcodeproj" 2>&1 || echo "无法列出scheme"
            
            echo ""
            echo "2. 尝试清理项目..."
            xcodebuild clean -project "123.xcodeproj" -scheme "$XCODE_SCHEME" -configuration Debug 2>&1 | tail -20 || echo "清理失败"
            
            echo ""
            echo "3. 尝试构建（无签名）..."
            xcodebuild build \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              2>&1 | tee build_test/simple_build.log
          else
            echo "❌ 没有可用的项目文件"
            exit 1
          fi
          
          echo "✅ 简单构建测试完成"
      
      # 4. 分析构建结果
      - name: Analyze build results
        script: |
          echo "=== 分析构建结果 ==="
          
          if [ -f "build_test/simple_build.log" ]; then
            echo "构建日志文件大小: $(wc -l < build_test/simple_build.log) 行"
            echo ""
            echo "最后50行日志:"
            tail -50 build_test/simple_build.log
            echo ""
            
            # 检查是否有错误
            echo "检查错误信息:"
            grep -i "error:" build_test/simple_build.log | head -20 || echo "未找到错误信息"
            echo ""
            
            # 检查是否有警告
            echo "检查警告信息:"
            grep -i "warning:" build_test/simple_build.log | head -10 || echo "未找到警告信息"
            echo ""
            
            # 检查是否成功
            if grep -q "BUILD SUCCEEDED" build_test/simple_build.log; then
              echo "✅ 构建成功"
              
              # 查找.app文件
              echo "查找生成的.app文件:"
              find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d 2>/dev/null | head -5 || echo "未找到.app文件"
            else
              echo "❌ 构建失败"
              
              # 显示更多错误信息
              echo "可能的关键错误:"
              grep -A 2 -B 2 -i "error:" build_test/simple_build.log | head -30 || echo "没有更多错误信息"
            fi
          else
            echo "❌ 未找到构建日志文件"
          fi
      
      # 5. 尝试使用xcodebuild的-showBuildSettings
      - name: Check build settings
        script: |
          echo "=== 检查构建设置 ==="
          
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace检查构建设置:"
            xcodebuild -showBuildSettings -workspace "123.xcworkspace" -scheme "$XCODE_SCHEME" 2>&1 | head -50 || echo "无法获取构建设置"
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project检查构建设置:"
            xcodebuild -showBuildSettings -project "123.xcodeproj" -scheme "$XCODE_SCHEME" 2>&1 | head -50 || echo "无法获取构建设置"
          fi
      
      # 6. 创建项目修复建议
      - name: Create project fix suggestions
        script: |
          echo "=== 项目修复建议 ==="
          
          # 创建修复建议文件
          cat > build_test/fix_suggestions.md << 'EOF'
          # iOS项目修复建议
          
          根据构建日志分析，以下可能是问题的原因和解决方案：
          
          ## 1. 检查Scheme配置
          - 在Xcode中打开项目
          - 点击顶部Scheme选择器
          - 选择"Manage Schemes..."
          - 确保有一个名为"123"的Scheme
          - 如果没有，点击"+"创建新Scheme
          
          ## 2. 检查Target配置
          - 在Xcode中，检查左侧项目导航器
          - 确保有名为"123"的Target
          - 检查Target的Build Settings
          
          ## 3. 检查Bundle Identifier
          - 在Xcode中，选择Target
          - 检查General标签页中的Bundle Identifier
          - 确保不是空的
          
          ## 4. 检查项目文件完整性
          - 确保所有源代码文件都存在
          - 检查是否有文件引用但实际不存在
          
          ## 5. 尝试创建新项目
          如果上述方法都失败，考虑：
          1. 在Xcode中创建新iOS项目
          2. 命名为"123"
          3. 复制现有源代码到新项目
          4. 重新配置
          
          ## 6. 检查CocoaPods配置（如果使用）
          - 确保Podfile存在且正确
          - 运行`pod install`
          - 使用生成的.xcworkspace文件
          
          EOF
          
          echo "✅ 修复建议已创建: build_test/fix_suggestions.md"
    
    artifacts:
      - build_test/
    
    publishing:
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
