workflows:
  ios-diagnostic:
    name: iOS Diagnostic Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "123"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
      cancel_previous_builds: false
    
    scripts:
      # 1. 恢复原始项目文件
      - name: Restore original project
        script: |
          echo "=== 恢复原始项目文件 ==="
          
          # 从git恢复所有文件
          echo "从git恢复项目文件..."
          git reset --hard HEAD
          git clean -fd
          
          # 显示项目结构
          echo "当前目录: $(pwd)"
          echo "项目结构:"
          ls -la
          
          # 验证项目文件
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "检查项目文件格式..."
            if plutil -lint 123.xcodeproj/project.pbxproj 2>/dev/null; then
              echo "✅ 项目文件格式有效"
            else
              echo "❌ 项目文件格式无效，尝试修复..."
              plutil -convert xml1 123.xcodeproj/project.pbxproj
              echo "修复完成"
            fi
          fi
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 测试基础编译（无签名）
      - name: Test basic compilation
        script: |
          echo "=== 测试基础编译（无签名）==="
          
          # 清理DerivedData
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
          # 尝试编译项目，禁用代码签名
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace编译..."
            
            # 清理
            xcodebuild clean -workspace "123.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Debug 2>&1 | tail -20 || echo "清理失败，继续..."
            
            # 编译（无签名）
            echo "编译项目..."
            xcodebuild build \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEVELOPMENT_TEAM="" \
              2>&1 | tee build/compile.log
            
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project编译..."
            
            # 清理
            xcodebuild clean -project "123.xcodeproj" -scheme "$XCODE_SCHEME" -configuration Debug 2>&1 | tail -20 || echo "清理失败，继续..."
            
            # 编译（无签名）
            echo "编译项目..."
            xcodebuild build \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Debug \
              -destination 'generic/platform=iOS' \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEVELOPMENT_TEAM="" \
              2>&1 | tee build/compile.log
          fi
      
      # 3. 分析编译结果
      - name: Analyze compilation
        script: |
          echo "=== 分析编译结果 ==="
          
          if [ -f "build/compile.log" ]; then
            echo "编译日志最后50行:"
            tail -50 build/compile.log
            echo ""
            
            # 检查是否成功
            if grep -q "BUILD SUCCEEDED" build/compile.log; then
              echo "✅ 编译成功"
              
              # 查找.app文件
              echo "查找编译产物..."
              find ~/Library/Developer/Xcode/DerivedData -name "*.app" -type d 2>/dev/null | head -5 || echo "未找到.app文件"
              
              # 检查是否有编译错误
              echo "编译错误:"
              grep -i "error:" build/compile.log | head -10 || echo "无编译错误"
            else
              echo "❌ 编译失败"
              
              # 显示详细的错误信息
              echo "详细错误:"
              grep -A 3 -B 3 -i "error:" build/compile.log | head -50 || echo "无详细错误信息"
              
              # 检查常见的编译问题
              echo "常见问题检查:"
              
              # 1. 检查是否缺少文件
              if grep -q "not found" build/compile.log; then
                echo "⚠️ 可能缺少文件"
                grep -i "not found" build/compile.log | head -5
              fi
              
              # 2. 检查是否有语法错误
              if grep -q "syntax" build/compile.log; then
                echo "⚠️ 可能有语法错误"
                grep -i "syntax" build/compile.log | head -5
              fi
              
              # 3. 检查是否有链接错误
              if grep -q "undefined symbol" build/compile.log; then
                echo "⚠️ 可能有链接错误"
                grep -i "undefined symbol" build/compile.log | head -5
              fi
            fi
          else
            echo "❌ 未找到编译日志"
          fi
      
      # 4. 检查项目配置
      - name: Check project configuration
        script: |
          echo "=== 检查项目配置 ==="
          
          # 检查scheme是否存在
          echo "检查scheme..."
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace检查scheme:"
            xcodebuild -list -workspace "123.xcworkspace" 2>&1 | head -30 || echo "无法检查scheme"
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project检查scheme:"
            xcodebuild -list -project "123.xcodeproj" 2>&1 | head -30 || echo "无法检查scheme"
          fi
          
          # 检查项目文件中的基本配置
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo ""
            echo "项目文件中的关键配置:"
            
            # 检查产品名称
            echo "产品名称:"
            grep -i "PRODUCT_NAME" 123.xcodeproj/project.pbxproj | head -3 || echo "未找到产品名称"
            
            # 检查bundle identifier
            echo "Bundle Identifier:"
            grep -i "PRODUCT_BUNDLE_IDENTIFIER" 123.xcodeproj/project.pbxproj | head -3 || echo "未找到Bundle Identifier"
            
            # 检查目标设备
            echo "目标设备:"
            grep -i "TARGETED_DEVICE_FAMILY\|IPHONEOS_DEPLOYMENT_TARGET" 123.xcodeproj/project.pbxproj | head -5 || echo "未找到目标设备配置"
          fi
      
      # 5. 创建修复建议
      - name: Create fix recommendations
        script: |
          echo "=== 创建修复建议 ==="
          
          # 创建诊断报告
          cat > build/diagnostic_report.txt << EOF
          iOS项目诊断报告
          生成时间: $(date)
          
          1. 项目结构:
          $(ls -la)
          
          2. 编译结果:
          $(if [ -f "build/compile.log" ]; then
            echo "最后状态:"
            tail -5 build/compile.log
          else
            echo "无编译日志"
          fi)
          
          3. 项目配置摘要:
          $(if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "产品名称: $(grep -m1 "PRODUCT_NAME = " 123.xcodeproj/project.pbxproj | cut -d= -f2 | tr -d ' ;' 2>/dev/null || echo '未找到')"
            echo "Bundle ID: $(grep -m1 "PRODUCT_BUNDLE_IDENTIFIER = " 123.xcodeproj/project.pbxproj | cut -d= -f2 | tr -d ' ;' 2>/dev/null || echo '未找到')"
          else
            echo "无项目配置文件"
          fi)
          
          4. 修复建议:
          
          如果编译失败:
          - 检查源代码是否有语法错误
          - 确保所有引用的文件都存在
          - 检查项目依赖是否正确配置
          
          如果代码签名失败:
          - 在Xcode中重新配置代码签名
          - 确保Bundle Identifier与配置文件匹配
          - 确保证书和配置文件有效
          
          建议步骤:
          1. 在本地用Xcode打开项目
          2. 尝试编译项目
          3. 检查并修复所有错误
          4. 确保可以成功运行
          5. 提交修复后的代码
          
          EOF
          
          echo "✅ 诊断报告已创建: build/diagnostic_report.txt"
    
    artifacts:
      - build/compile.log
      - build/diagnostic_report.txt
    
    publishing:
      email:
        recipients:
          - "717@stlnd.net"
        notify:
          success: true
          failure: true
