workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
        
        # 代码签名配置
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_NAME: "codemagic_Production"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    
    scripts:
      # 1. 设置环境和显示证书信息
      - name: Setup environment
        script: |
          echo "=== 设置环境 ==="
          echo "当前目录: $(pwd)"
          echo "Scheme: $XCODE_SCHEME"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $APP_IDENTIFIER"
          echo "代码签名身份: $CODE_SIGN_IDENTITY"
          echo "配置文件: $PROVISIONING_PROFILE_NAME"
          
          # 显示项目结构
          echo "项目结构:"
          ls -la
          
          # 显示所有可用证书
          echo "所有可用证书:"
          security find-identity -p codesigning -v
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 使用构建参数覆盖签名配置（不修改项目文件）
      - name: Build archive with override parameters
        script: |
          echo "=== 使用构建参数覆盖签名配置 ==="
          
          # 清理之前的构建
          rm -rf build/*.xcarchive
          
          # 检查证书是否可用
          echo "检查证书 '$CODE_SIGN_IDENTITY' 是否可用..."
          if security find-identity -p codesigning -v | grep -q "$CODE_SIGN_IDENTITY"; then
            echo "✅ 找到证书: $CODE_SIGN_IDENTITY"
          else
            echo "❌ 未找到证书: $CODE_SIGN_IDENTITY"
            echo "可用证书:"
            security find-identity -p codesigning -v
            exit 1
          fi
          
          # 构建archive，通过构建参数覆盖签名配置
          echo "构建archive..."
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace构建..."
            
            xcodebuild archive \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              DEVELOPMENT_TEAM="$TEAM_ID" \
              PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
              CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
              PRODUCT_BUNDLE_IDENTIFIER="$APP_IDENTIFIER" \
              2>&1 | tee build/archive.log
            
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project构建..."
            
            xcodebuild archive \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              DEVELOPMENT_TEAM="$TEAM_ID" \
              PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
              CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
              PRODUCT_BUNDLE_IDENTIFIER="$APP_IDENTIFIER" \
              2>&1 | tee build/archive.log
          fi
          
          # 检查archive是否成功
          if [ -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "✅ archive构建成功"
            
            # 显示archive中的app签名信息
            echo "检查archive中的签名..."
            APP_PATH="build/$XCODE_SCHEME.xcarchive/Products/Applications/$XCODE_SCHEME.app"
            if [ -d "$APP_PATH" ]; then
              echo "应用签名信息:"
              codesign -d -vvv "$APP_PATH" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier" || echo "无法获取签名详情"
            else
              echo "⚠️ 未找到.app文件"
              echo "Archive内容:"
              find "build/$XCODE_SCHEME.xcarchive" -type f -name "*.app" 2>/dev/null || echo "无.app文件"
            fi
          else
            echo "❌ archive构建失败"
            echo "查看日志最后100行:"
            tail -100 build/archive.log
            exit 1
          fi
      
      # 3. 导出IPA
      - name: Export IPA
        script: |
          echo "=== 导出IPA ==="
          
          # 清理之前的IPA
          rm -rf build/*.ipa
          
          # 创建export_options.plist
          cat > build/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_IDENTIFIER</key>
                  <string>$PROVISIONING_PROFILE_NAME</string>
              </dict>
              <key>signingCertificate</key>
              <string>$CODE_SIGN_IDENTITY</string>
          </dict>
          </plist>
          EOF
          
          echo "export_options.plist内容:"
          cat build/export_options.plist
          
          # 执行导出
          echo "开始导出IPA..."
          xcodebuild -exportArchive \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist "build/export_options.plist" \
            -exportPath "build" \
            -allowProvisioningUpdates \
            2>&1 | tee build/export.log
          
          echo "✅ 导出完成"
      
      # 4. 验证和重命名IPA文件
      - name: Verify and rename IPA
        script: |
          echo "=== 验证和重命名IPA文件 ==="
          
          # 查找生成的IPA文件
          echo "查找IPA文件..."
          IPA_FILES=$(find build -name "*.ipa" 2>/dev/null)
          
          if [ -z "$IPA_FILES" ]; then
            echo "❌ 未找到IPA文件"
            echo "导出日志最后100行:"
            tail -100 build/export.log || echo "无导出日志"
            exit 1
          fi
          
          echo "找到的IPA文件:"
          echo "$IPA_FILES"
          
          # 如果IPA文件不在根目录，移动到根目录
          if [ ! -f "build/$XCODE_SCHEME.ipa" ]; then
            FIRST_IPA=$(echo "$IPA_FILES" | head -1)
            echo "将IPA文件复制到标准位置: $FIRST_IPA -> build/$XCODE_SCHEME.ipa"
            cp "$FIRST_IPA" "build/$XCODE_SCHEME.ipa"
          fi
          
          # 验证IPA文件
          if [ -f "build/$XCODE_SCHEME.ipa" ]; then
            echo "✅ IPA文件创建成功: build/$XCODE_SCHEME.ipa"
            echo "文件大小: $(du -h "build/$XCODE_SCHEME.ipa" | cut -f1)"
            
            # 验证签名
            echo "验证IPA签名..."
            codesign -d -vvv "build/$XCODE_SCHEME.ipa" 2>&1 | head -20 || echo "无法验证IPA签名"
          else
            echo "❌ IPA文件未创建"
            exit 1
          fi
      
      # 5. 显示构建摘要
      - name: Build summary
        script: |
          echo "=== 构建摘要 ==="
          echo "✅ 构建成功!"
          echo ""
          echo "生成的产物:"
          echo "IPA: build/$XCODE_SCHEME.ipa"
          echo "Archive: build/$XCODE_SCHEME.xcarchive"
          echo ""
          echo "文件大小:"
          du -h "build/$XCODE_SCHEME.ipa" 2>/dev/null || echo "IPA文件不存在"
          du -h "build/$XCODE_SCHEME.xcarchive" 2>/dev/null || echo "Archive不存在"
          echo ""
          echo "构建完成时间: $(date)"
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - build/export_options.plist
      - build/archive.log
      - build/export.log
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "717@stln.net"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
