workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_signing  # 这个组包含代码签名证书
        - appstore_connect  # 这个组包含App Store Connect API密钥
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
        XCODE_WORKSPACE: "123.xcworkspace"  # 根据实际情况调整
        
        # 代码签名配置（从Codemagic UI获取）
        CODE_SIGNING_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_NAME: "codemagic_Production"
        
        # App Store Connect API密钥ID（从截图获取）
        API_KEY_ID: "4BJ4P56482"
        
        # 构建版本号（可选）
        BUILD_NUMBER: "$(date +%s)"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
        - vendor/bundle
    
    scripts:
      # 1. 安装依赖
      - name: Install dependencies
        script: |
          echo "=== 安装依赖 ==="
          
          # 检查并安装CocoaPods依赖
          if [ -f "Podfile" ]; then
            echo "安装CocoaPods依赖..."
            pod install
          else
            echo "未找到Podfile"
          fi
          
          # 安装fastlane
          sudo gem install fastlane -NV
          
          # 创建必要目录
          mkdir -p fastlane
          mkdir -p build
      
      # 2. 准备代码签名
      - name: Prepare code signing
        script: |
          echo "=== 准备代码签名 ==="
          echo "团队ID: $TEAM_ID"
          echo "API密钥ID: $API_KEY_ID"
          echo "应用标识符: $APP_IDENTIFIER"
          
          # 验证代码签名证书
          echo "可用的证书:"
          security find-identity -p codesigning -v | grep "Distribution" || true
          
          # 验证配置文件
          echo "已安装的配置文件:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ | grep -i "$PROVISIONING_PROFILE_NAME" || true
      
      # 3. 创建fastlane配置
      - name: Configure fastlane
        script: |
          echo "=== 配置fastlane ==="
          
          # 创建Appfile
          cat > fastlane/Appfile << EOF
          app_identifier "$APP_IDENTIFIER"
          apple_id "$APPLE_ID"
          team_id "$TEAM_ID"
          itc_team_id "$TEAM_ID"
          EOF
          
          # 创建Fastfile
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            lane :build_and_upload do
              # 设置构建号（可选）
              # increment_build_number(build_number: ENV['BUILD_NUMBER']) if ENV['BUILD_NUMBER']
              
              # 构建IPA
              gym(
                workspace: "$XCODE_WORKSPACE",
                scheme: "$XCODE_SCHEME",
                configuration: "Release",
                output_directory: "../build",
                output_name: "$XCODE_SCHEME.ipa",
                export_method: "app-store",
                export_options: {
                  provisioningProfiles: {
                    "$APP_IDENTIFIER" => "$PROVISIONING_PROFILE_NAME"
                  },
                  signingCertificate: "$CODE_SIGNING_IDENTITY",
                  teamID: "$TEAM_ID"
                },
                clean: true,
                silent: false
              )
              
              # 验证IPA
              verify_build(
                app_identifier: "$APP_IDENTIFIER"
              )
            end
          end
          EOF
          
          echo "✅ Fastlane配置完成"
      
      # 4. 构建应用
      - name: Build iOS app
        script: |
          echo "=== 开始构建应用 ==="
          
          # 进入fastlane目录构建
          cd fastlane
          fastlane ios build_and_upload
          cd ..
          
          echo "✅ 构建完成"
      
      # 5. 验证构建产物
      - name: Verify artifacts
        script: |
          echo "=== 验证构建产物 ==="
          
          IPA_PATH="build/$XCODE_SCHEME.ipa"
          
          if [ -f "$IPA_PATH" ]; then
            echo "✅ IPA文件: $IPA_PATH"
            echo "文件大小: $(du -h "$IPA_PATH" | cut -f1)"
            
            # 验证文件结构
            echo "IPA内容:"
            unzip -l "$IPA_PATH" | grep -E "\.app/$" | head -5
          else
            echo "❌ 未找到IPA文件"
            find . -name "*.ipa" 2>/dev/null || true
            exit 1
          fi
    
    artifacts:
      - build/*.ipa
      - fastlane/Appfile
      - fastlane/Fastfile
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        # 使用环境变量中的API密钥
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        # 提交到TestFlight
        submit_to_testflight: true
        
        # 可以选择不直接提交到App Store
        submit_to_app_store: false
        
        # 测试组
        beta_groups:
          - "Internal Testers"
