workflows:
  ios-final:
    name: iOS Final
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
        XCODE_SCHEME: "123"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    
    scripts:
      - name: 构建
        script: |
          # 安装依赖
          [ -f "Podfile" ] && pod install || true
          
          # 代码签名
          xcode-project use-profiles
          
          # 构建
          xcode-project build-ipa \
            --workspace "123.xcworkspace" \
            --scheme "$XCODE_SCHEME"
      
      - name: 验证
        script: |
          # 简单验证
          if [ -f "build/ios/ipa/123.ipa" ]; then
            echo "构建成功!"
          else
            echo "构建失败"
            exit 1
          fi
    
    artifacts:
      - build/ios/ipa/123.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
