workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_signing
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
        
        # 项目配置 - 根据实际情况调整
        # 如果使用 workspace:
        XCODE_WORKSPACE: "123.xcworkspace"
        # 如果使用 project (二选一):
        # XCODE_PROJECT: "123.xcodeproj"
        
        # 代码签名配置
        CODE_SIGNING_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_NAME: "codemagic_Production"
        
        # App Store Connect API 密钥 ID
        API_KEY_ID: "4BJ4P56482"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
        - vendor/bundle
    
    scripts:
      # 1. 安装依赖
      - name: Install dependencies
        script: |
          echo "=== 安装依赖 ==="
          echo "当前目录: $(pwd)"
          echo "目录内容:"
          ls -la
          
          # 检查项目结构
          echo "检查Xcode项目..."
          if [ -f "Podfile" ]; then
            echo "安装CocoaPods依赖..."
            pod install
          else
            echo "未找到Podfile，跳过CocoaPods安装"
          fi
          
          # 安装fastlane（备用）
          sudo gem install fastlane -NV
          
          # 创建必要目录
          mkdir -p build
          mkdir -p fastlane
          
          echo "✅ 依赖安装完成"
      
      # 2. 准备代码签名
      - name: Prepare code signing
        script: |
          echo "=== 准备代码签名 ==="
          
          # 显示所有可用证书
          echo "系统钥匙串中的证书:"
          security list-keychains
          security find-identity -p codesigning -v
          
          # 检查配置文件
          echo "配置文件目录:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "配置文件目录不存在"
          
          # 创建export_options.plist文件
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_IDENTIFIER</key>
                  <string>$PROVISIONING_PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          EOF
          
          echo "✅ 代码签名准备完成"
      
      # 3. 尝试使用Codemagic内置工具构建
      - name: Build with Codemagic tools
        script: |
          echo "=== 使用Codemagic工具构建 ==="
          
          # 检查项目文件
          echo "检查Xcode项目文件..."
          if [ -n "$XCODE_WORKSPACE" ] && [ -f "$XCODE_WORKSPACE" ]; then
            echo "使用workspace: $XCODE_WORKSPACE"
            PROJECT_ARG="--workspace $XCODE_WORKSPACE"
          elif [ -n "$XCODE_PROJECT" ] && [ -f "$XCODE_PROJECT" ]; then
            echo "使用project: $XCODE_PROJECT"
            PROJECT_ARG="--project $XCODE_PROJECT"
          else
            echo "❌ 未找到Xcode项目文件"
            echo "当前目录内容:"
            ls -la
            exit 1
          fi
          
          # 使用Codemagic工具构建
          echo "开始构建IPA..."
          xcode-project use-profiles
          
          # 尝试构建
          xcode-project build-ipa \
            $PROJECT_ARG \
            --scheme "$XCODE_SCHEME" \
            --output "build" \
            --archive-flags "-destination 'generic/platform=iOS' -allowProvisioningUpdates" \
            --export-options-plist "export_options.plist" \
            --disable-codesign false
          
          echo "✅ 构建完成"
      
      # 4. 备用方案：使用fastlane构建
      - name: Build with fastlane (fallback)
        when: always  # 只有在主构建失败时才运行
        script: |
          echo "=== 尝试使用fastlane构建 (备用方案) ==="
          
          # 创建fastlane配置
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            lane :build do
              # 构建配置
              if ENV['XCODE_WORKSPACE']
                gym(
                  workspace: ENV['XCODE_WORKSPACE'],
                  scheme: ENV['XCODE_SCHEME'],
                  configuration: "Release",
                  output_directory: "../build",
                  output_name: "\#{ENV['XCODE_SCHEME']}.ipa",
                  export_method: "app-store",
                  export_options: {
                    provisioningProfiles: {
                      ENV['APP_IDENTIFIER'] => ENV['PROVISIONING_PROFILE_NAME']
                    }
                  },
                  clean: true
                )
              else
                gym(
                  project: ENV['XCODE_PROJECT'],
                  scheme: ENV['XCODE_SCHEME'],
                  configuration: "Release",
                  output_directory: "../build",
                  output_name: "\#{ENV['XCODE_SCHEME']}.ipa",
                  export_method: "app-store",
                  export_options: {
                    provisioningProfiles: {
                      ENV['APP_IDENTIFIER'] => ENV['PROVISIONING_PROFILE_NAME']
                    }
                  },
                  clean: true
                )
              end
            end
          end
          EOF
          
          # 运行fastlane构建
          cd fastlane
          fastlane ios build
          cd ..
          
          echo "✅ Fastlane构建完成"
      
      # 5. 验证构建产物
      - name: Verify artifacts
        script: |
          echo "=== 验证构建产物 ==="
          
          # 查找所有IPA文件
          echo "搜索IPA文件..."
          find . -name "*.ipa" -type f 2>/dev/null || true
          
          # 检查预期的IPA路径
          EXPECTED_IPA="build/$XCODE_SCHEME.ipa"
          if [ -f "$EXPECTED_IPA" ]; then
            echo "✅ 找到IPA文件: $EXPECTED_IPA"
            echo "文件大小: $(du -h "$EXPECTED_IPA" | cut -f1)"
            
            # 验证IPA结构
            echo "IPA内容预览:"
            unzip -l "$EXPECTED_IPA" | head -20
          else
            echo "⚠️ 未在预期路径找到IPA: $EXPECTED_IPA"
            
            # 尝试查找其他位置的IPA
            FOUND_IPA=$(find . -name "*.ipa" -type f | head -1)
            if [ -n "$FOUND_IPA" ]; then
              echo "✅ 在其他位置找到IPA: $FOUND_IPA"
              # 复制到build目录
              mkdir -p build
              cp "$FOUND_IPA" "$EXPECTED_IPA"
              echo "已复制到: $EXPECTED_IPA"
            else
              echo "❌ 未找到任何IPA文件"
              echo "build目录内容:"
              ls -la build/ 2>/dev/null || echo "build目录不存在"
              echo "构建日志结束"
              exit 1
            fi
          fi
    
    artifacts:
      - build/*.ipa
      - export_options.plist
      - fastlane/Fastfile 2>/dev/null || true
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
