# codemagic.yaml
workflows:
  ios-release:
    name: iOS App Store Release
    environment:
      xcode: latest
      groups:
        - appstore_signing
        - appstore_connect  # 添加 App Store Connect API 密钥组
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        SCHEME: "123"
        
        # 版本管理（可选）
        BUILD_NUMBER: "$(date +%Y%m%d%H%M)"  # 自动生成构建号
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      paths:
        - vendor/bundle  # 缓存 fastlane gems
        - fastlane/logs
    
    scripts:
      - name: Setup fastlane environment
        script: |
          echo "=== Setting up fastlane ==="
          echo "App: $APP_IDENTIFIER"
          echo "Team: $TEAM_ID"
          echo "Scheme: $SCHEME"
          
          # 安装 fastlane（如果已缓存会更快）
          sudo gem install fastlane -NV
          
          # 创建 fastlane 目录
          mkdir -p fastlane
      
      - name: Configure fastlane
        script: |
          echo "=== Creating fastlane configuration ==="
          
          # 1. Appfile - 应用配置
          cat > fastlane/Appfile << EOF
          # 应用标识符
          app_identifier "$APP_IDENTIFIER"
          
          # Apple ID
          apple_id "$APPLE_ID"
          
          # 团队 ID
          team_id "$TEAM_ID"
          
          # 可选：iTunes Connect 团队（如果有多个团队）
          # itc_team_id "$TEAM_ID"
          EOF
          
          # 2. Fastfile - 构建流程
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            # 发布到 App Store 的完整流程
            lane :release do |options|
              # 可选：设置构建号
              if ENV['BUILD_NUMBER']
                increment_build_number(
                  build_number: ENV['BUILD_NUMBER']
                )
              end
              
              # 构建 IPA
              gym(
                # 项目配置
                workspace: "$SCHEME.xcworkspace",
                scheme: "$SCHEME",
                configuration: "Release",
                
                # 输出配置
                output_directory: "../build",
                output_name: "$SCHEME.ipa",
                
                # 导出配置
                export_method: "app-store",
                export_options: {
                  method: "app-store",
                  teamID: "$TEAM_ID",
                  uploadBitcode: false,
                  compileBitcode: false,
                  uploadSymbols: true,
                  provisioningProfiles: {
                    "$APP_IDENTIFIER" => "codemagic Production"
                  }
                },
                
                # 其他选项
                clean: true,
                silent: false,
                skip_package_ipa: false,
                skip_archive: false,
                include_symbols: true,
                include_bitcode: false
              )
              
              # 验证构建
              verify_build(
                app_identifier: "$APP_IDENTIFIER"
              )
            end
            
            # 快速测试构建
            lane :test_build do
              gym(
                workspace: "$SCHEME.xcworkspace",
                scheme: "$SCHEME",
                configuration: "Debug",
                clean: true,
                skip_package_ipa: false
              )
            end
          end
          EOF
          
          echo "✅ Fastlane configuration created"
      
      - name: Run fastlane release build
        script: |
          echo "=== Starting fastlane release build ==="
          
          # 进入 fastlane 目录
          cd fastlane
          
          # 运行 release lane
          fastlane ios release
          
          # 返回项目根目录
          cd ..
          
          echo "✅ Fastlane build completed"
      
      - name: Verify build artifacts
        script: |
          echo "=== Verifying build artifacts ==="
          
          # 检查 IPA 文件
          if [ -f "build/$SCHEME.ipa" ]; then
            IPA_FILE="build/$SCHEME.ipa"
          else
            # 查找任何 IPA 文件
            IPA_FILE=$(find . -name "*.ipa" -type f | head -1)
          fi
          
          if [ -n "$IPA_FILE" ] && [ -f "$IPA_FILE" ]; then
            echo "✅ IPA file found: $IPA_FILE"
            echo "File size: $(du -h "$IPA_FILE" | cut -f1)"
            
            # 验证 IPA 内容
            echo "IPA content overview:"
            unzip -l "$IPA_FILE" | grep "Payload/" | head -5
            
            # 确保在 build 目录
            mkdir -p build
            if [ "$IPA_FILE" != "build/$SCHEME.ipa" ]; then
              cp "$IPA_FILE" "build/$SCHEME.ipa"
              echo "✅ IPA copied to build directory"
            fi
          else
            echo "❌ No IPA file found"
            echo "Searching for files:"
            find . -name "*.ipa" -type f
            exit 1
          fi
      
      - name: Prepare for App Store Connect
        script: |
          echo "=== Preparing for App Store Connect ==="
          
          # 检查是否配置了 App Store Connect API 密钥
          if [ -z "$APP_STORE_CONNECT_API_KEY" ] || \
             [ -z "$APP_STORE_CONNECT_KEY_IDENTIFIER" ] || \
             [ -z "$APP_STORE_CONNECT_ISSUER_ID" ]; then
            echo "⚠️ App Store Connect API keys not configured"
            echo "Build will complete but won't be uploaded to App Store Connect"
          else
            echo "✅ App Store Connect API keys configured"
            
            # 创建 fastlane API 密钥配置
            cat > fastlane/AppStoreConnectApiKey.json << EOF
            {
              "key_id": "$APP_STORE_CONNECT_KEY_IDENTIFIER",
              "issuer_id": "$APP_STORE_CONNECT_ISSUER_ID",
              "key": "$APP_STORE_CONNECT_API_KEY",
              "duration": 1200,
              "in_house": false
            }
            EOF
            
            echo "App Store Connect API key file created"
          fi
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - fastlane/Appfile
      - fastlane/Fastfile
      - fastlane/logs/*.log
      - fastlane/README.md
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到 App Store Connect (TestFlight)
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:  # 可选：测试组
          - "Internal Testers"
        # 可选：自动提交到 App Store Review
        # submit_to_app_store: false
        # 可选：跳过等待处理完成
        # skip_waiting_for_build_processing: false
      
      # 可选：发布到 Firebase App Distribution
      # firebase:
      #   firebase_token: $FIREBASE_TOKEN
      #   app_id: $FIREBASE_APP_ID
      #   groups:
      #     - testers
      
      # 可选：发布到 Slack
      # slack:
      #   channel: '#ios-builds'
      #   webhook: $SLACK_WEBHOOK_URL
