workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    
    scripts:
      # 1. 设置环境和验证
      - name: Setup and verify
        script: |
          echo "=== 设置和验证 ==="
          echo "当前目录: $(pwd)"
          echo "Scheme: $XCODE_SCHEME"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $APP_IDENTIFIER"
          
          # 显示项目结构
          echo "项目结构:"
          ls -la
          
          # 验证项目文件
          if [ -d "123.xcworkspace" ]; then
            echo "✅ 使用workspace: 123.xcworkspace"
            echo "检查workspace的scheme:"
            xcodebuild -list -workspace "123.xcworkspace" 2>&1 | grep -A 20 "Schemes:" || echo "无法列出scheme"
          elif [ -d "123.xcodeproj" ]; then
            echo "✅ 使用project: 123.xcodeproj"
            echo "检查project的scheme:"
            xcodebuild -list -project "123.xcodeproj" 2>&1 | grep -A 20 "Schemes:" || echo "无法列出scheme"
          else
            echo "❌ 未找到项目文件"
            exit 1
          fi
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 手动设置代码签名（不使用Codemagic特定工具）
      - name: Manual code signing setup
        script: |
          echo "=== 手动设置代码签名 ==="
          
          # 显示可用证书
          echo "可用证书:"
          security find-identity -p codesigning -v
          
          # 创建临时钥匙串并导入证书（如果需要）
          # 注意：这里假设证书已在系统钥匙串中，或由Codemagic自动配置
          
          echo "✅ 代码签名准备完成"
      
      # 3. 修正项目文件中的配置问题
      - name: Fix project configuration
        script: |
          echo "=== 修正项目配置 ==="
          
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "备份项目文件..."
            cp 123.xcodeproj/project.pbxproj 123.xcodeproj/project.pbxproj.backup
            
            # 确保有正确的开发团队设置
            echo "检查并设置开发团队..."
            if ! grep -q "DEVELOPMENT_TEAM = $TEAM_ID" 123.xcodeproj/project.pbxproj; then
              echo "设置开发团队为: $TEAM_ID"
              # 替换现有的DEVELOPMENT_TEAM设置，或添加新的
              sed -i '' "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = $TEAM_ID;/g" 123.xcodeproj/project.pbxproj 2>/dev/null || \
              sed -i '' "/Begin PBXProject section/,/End PBXProject section/ s/attributes = {/attributes = { DEVELOPMENT_TEAM = $TEAM_ID;/" 123.xcodeproj/project.pbxproj
            fi
            
            # 确保有正确的bundle identifier
            echo "检查并设置bundle identifier..."
            if ! grep -q "PRODUCT_BUNDLE_IDENTIFIER = $APP_IDENTIFIER" 123.xcodeproj/project.pbxproj; then
              echo "设置bundle identifier为: $APP_IDENTIFIER"
              sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $APP_IDENTIFIER;/g" 123.xcodeproj/project.pbxproj
            fi
            
            # 移除可能导致问题的provisioning profile设置（让Xcode自动选择）
            echo "移除固定的provisioning profile设置（使用自动选择）..."
            sed -i '' '/PROVISIONING_PROFILE/d' 123.xcodeproj/project.pbxproj
            sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' 123.xcodeproj/project.pbxproj
            
            echo "✅ 项目配置修正完成"
          else
            echo "⚠️ 未找到项目配置文件，跳过配置修正"
          fi
      
      # 4. 构建archive（使用自动代码签名）
      - name: Build archive with auto signing
        script: |
          echo "=== 构建archive（自动代码签名）==="
          
          # 清理之前的构建
          rm -rf build/*.xcarchive
          
          # 创建build目录
          mkdir -p build
          
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace构建..."
            
            # 构建archive，使用自动代码签名
            xcodebuild archive \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              CODE_SIGN_STYLE="Automatic" \
              2>&1 | tee build/archive.log
            
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project构建..."
            
            # 构建archive，使用自动代码签名
            xcodebuild archive \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              CODE_SIGN_STYLE="Automatic" \
              2>&1 | tee build/archive.log
          fi
          
          # 检查archive是否成功
          if [ -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "✅ archive构建成功"
          else
            echo "❌ archive构建失败"
            echo "查看日志:"
            tail -50 build/archive.log
            exit 1
          fi
      
      # 5. 导出IPA
      - name: Export IPA
        script: |
          echo "=== 导出IPA ==="
          
          # 清理之前的IPA
          rm -rf build/*.ipa
          
          # 创建export_options.plist（使用app-store方法）
          cat > build/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_IDENTIFIER</key>
                  <string>codemagic_Production</string>
              </dict>
          </dict>
          </plist>
          EOF
          
          echo "export_options.plist内容:"
          cat build/export_options.plist
          
          # 执行导出
          xcodebuild -exportArchive \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist "build/export_options.plist" \
            -exportPath "build" \
            -allowProvisioningUpdates \
            2>&1 | tee build/export.log
          
          echo "✅ 导出完成"
      
      # 6. 验证和重命名IPA文件
      - name: Verify and rename IPA
        script: |
          echo "=== 验证和重命名IPA文件 ==="
          
          # 查找生成的IPA文件
          echo "查找IPA文件..."
          IPA_FILES=$(find build -name "*.ipa" 2>/dev/null)
          
          if [ -z "$IPA_FILES" ]; then
            echo "❌ 未找到IPA文件"
            echo "导出日志最后50行:"
            tail -50 build/export.log || echo "无导出日志"
            exit 1
          fi
          
          echo "找到的IPA文件:"
          echo "$IPA_FILES"
          
          # 如果IPA文件不在根目录，移动到根目录
          if [ ! -f "build/$XCODE_SCHEME.ipa" ]; then
            FIRST_IPA=$(echo "$IPA_FILES" | head -1)
            echo "将IPA文件复制到标准位置: $FIRST_IPA -> build/$XCODE_SCHEME.ipa"
            cp "$FIRST_IPA" "build/$XCODE_SCHEME.ipa"
          fi
          
          # 验证IPA文件
          if [ -f "build/$XCODE_SCHEME.ipa" ]; then
            echo "✅ IPA文件创建成功: build/$XCODE_SCHEME.ipa"
            echo "文件大小: $(du -h "build/$XCODE_SCHEME.ipa" | cut -f1)"
            
            # 显示文件信息
            echo "文件信息:"
            ls -la "build/$XCODE_SCHEME.ipa"
          else
            echo "❌ IPA文件未创建"
            exit 1
          fi
      
      # 7. 显示构建摘要
      - name: Build summary
        script: |
          echo "=== 构建摘要 ==="
          echo "✅ 构建成功!"
          echo ""
          echo "生成的产物:"
          echo "IPA: build/$XCODE_SCHEME.ipa"
          echo "Archive: build/$XCODE_SCHEME.xcarchive"
          echo ""
          echo "文件大小:"
          du -h "build/$XCODE_SCHEME.ipa" 2>/dev/null || echo "IPA文件不存在"
          du -h "build/$XCODE_SCHEME.xcarchive" 2>/dev/null || echo "Archive不存在"
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - build/export_options.plist
      - build/archive.log
      - build/export.log
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
