# codemagic.yaml
workflows:
  ios-release:
    name: iOS App Store Release
    environment:
      xcode: latest
      # 只需要证书，不需要描述文件
      groups:
        - appstore_signing
      vars:
        SCHEME: "123"
        TEAM_ID: "7994453ZHZ"
    
    scripts:
      - name: Setup certificate only
        script: |
          echo "=== Setting up certificate for automatic signing ==="
          
          # 下载证书
          curl -L -s -o certificate.p12 "$APPSTORE_CERTIFICATE_URL"
          
          # 创建简单的钥匙串
          KEYCHAIN_PATH="$HOME/Library/Keychains/auto-sign.keychain"
          KEYCHAIN_PASSWORD="auto123"
          
          # 清理并创建
          security delete-keychain "$KEYCHAIN_PATH" 2>/dev/null || true
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          
          # 导入证书
          security import certificate.p12 \
            -k "$KEYCHAIN_PATH" \
            -P "$APPSTORE_CERTIFICATE_PASSWORD" \
            -T /usr/bin/codesign \
            -A
          
          # 简单权限设置
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          echo "✅ Certificate ready for automatic signing"
      
      - name: Let Xcode handle provisioning automatically
        script: |
          echo "=== Letting Xcode handle provisioning automatically ==="
          
          # 清理
          rm -rf build 2>/dev/null || true
          mkdir -p build
          
          echo "Xcode will automatically download and manage provisioning profiles"
          echo "Team ID: $TEAM_ID"
          
          # **关键：使用自动签名，让 Xcode 处理一切**
          xcodebuild archive \
            -workspace "123.xcworkspace" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "build/$SCHEME.xcarchive" \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE="Automatic" \
            DEVELOPMENT_TEAM="$TEAM_ID"
          
          if [ -d "build/$SCHEME.xcarchive" ]; then
            echo "✅ Archive created with automatic signing!"
          else
            echo "❌ Archive failed"
            exit 1
          fi
      
      - name: Export with automatic signing
        script: |
          echo "=== Exporting IPA ==="
          
          # 自动签名的导出配置
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>uploadBitcode</key>
              <true/>
              <key>compileBitcode</true/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath "build/$SCHEME.xcarchive" \
            -exportPath "build" \
            -exportOptionsPlist "exportOptions.plist" \
            -allowProvisioningUpdates
          
          if ls build/*.ipa 1> /dev/null 2>&1; then
            echo "✅ IPA exported successfully!"
            ls -lh build/*.ipa
          else
            echo "❌ IPA export failed"
            exit 1
          fi
    
    artifacts:
      - build/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
