# codemagic.yaml - 简化版
workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      groups:
        - appstore_signing
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
        SCHEME: "123"
        TEAM_ID: "7994453ZHZ"  # 获取方法见下文
    
    # 如果您的项目在 ios 目录下
    ios:
      project: "ios/123.xcodeproj"  # 或 "ios/123.xcworkspace"
      scheme: "$SCHEME"
    
    scripts:
      - name: Build iOS app
        script: |
          cd ios
          
          # 自动检测使用 workspace 还是 project
          if [ -f "$SCHEME.xcworkspace" ]; then
            echo "Building with workspace: $SCHEME.xcworkspace"
            xcode-project build-ipa \
              --workspace "$SCHEME.xcworkspace" \
              --scheme "$SCHEME" \
              --export-options-plist "exportOptions.plist"
          else
            echo "Building with project: $SCHEME.xcodeproj"
            xcode-project build-ipa \
              --project "$SCHEME.xcodeproj" \
              --scheme "$SCHEME" \
              --export-options-plist "exportOptions.plist"
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
