workflows:
  ios-success:
    name: iOS Success
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
        XCODE_SCHEME: "123"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    
    scripts:
      - name: 安装依赖
        script: |
          [ -f "Podfile" ] && pod install || echo "没有Podfile"
      
      - name: 构建
        script: |
          echo "构建IPA..."
          xcode-project build-ipa \
            --workspace "123.xcworkspace" \
            --scheme "$XCODE_SCHEME"
          
          echo "检查构建结果:"
          ls -la build/ios/ipa/
      
      - name: 准备发布
        script: |
          echo "准备发布..."
          mkdir -p dist
          cp build/ios/ipa/123.ipa dist/
    
    artifacts:
      - dist/123.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
