workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
        - vendor/bundle
    
    scripts:
      # 1. 恢复项目文件备份（如果存在）
      - name: Restore project from backup
        script: |
          echo "=== 恢复项目文件 ==="
          
          if [ -f "123.xcodeproj/project.pbxproj.backup" ]; then
            echo "恢复项目文件备份..."
            cp 123.xcodeproj/project.pbxproj.backup 123.xcodeproj/project.pbxproj
            echo "✅ 项目文件已从备份恢复"
          else
            echo "⚠️ 未找到项目文件备份"
            # 从git恢复原始文件
            echo "尝试从git恢复项目文件..."
            git checkout HEAD -- 123.xcodeproj/project.pbxproj 2>/dev/null || echo "无法从git恢复"
          fi
          
          # 验证项目文件
          echo "验证项目文件格式..."
          if plutil -lint 123.xcodeproj/project.pbxproj 2>/dev/null; then
            echo "✅ 项目文件格式有效"
          else
            echo "❌ 项目文件格式无效"
            echo "尝试修复项目文件..."
            plutil -convert xml1 123.xcodeproj/project.pbxproj 2>/dev/null || echo "无法修复项目文件"
          fi
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 使用fastlane构建（它会自动处理代码签名）
      - name: Setup and run fastlane
        script: |
          echo "=== 使用fastlane构建 ==="
          
          # 安装fastlane
          echo "安装fastlane..."
          sudo gem install fastlane -NV
          
          # 创建fastlane目录
          mkdir -p fastlane
          
          # 创建Appfile
          cat > fastlane/Appfile << EOF
          # 应用标识符
          app_identifier "$APP_IDENTIFIER"
          
          # Apple ID
          apple_id "$APPLE_ID"
          
          # 团队ID
          team_id "$TEAM_ID"
          
          # iTunes Connect团队
          itc_team_id "$TEAM_ID"
          EOF
          
          # 创建Fastfile
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            lane :release do
              # 构建IPA
              gym(
                # 项目配置
                workspace: "123.xcworkspace",
                scheme: "$XCODE_SCHEME",
                configuration: "Release",
                
                # 输出配置
                output_directory: "../build",
                output_name: "$XCODE_SCHEME.ipa",
                
                # 导出配置
                export_method: "app-store",
                export_options: {
                  uploadBitcode: false,
                  compileBitcode: false
                },
                
                # 其他选项
                clean: true,
                silent: false,
                skip_package_ipa: false,
                include_symbols: true,
                include_bitcode: false,
                
                # 代码签名配置 - 让fastlane自动处理
                export_xcargs: "-allowProvisioningUpdates"
              )
              
              # 验证构建
              verify_build(
                app_identifier: "$APP_IDENTIFIER"
              )
            end
            
            # 调试用的lane
            lane :debug_build do
              # 测试构建
              gym(
                workspace: "123.xcworkspace",
                scheme: "$XCODE_SCHEME",
                configuration: "Debug",
                export_method: "development",
                output_directory: "../build",
                output_name: "$XCODE_SCHEME-debug.ipa",
                clean: true
              )
            end
          end
          EOF
          
          echo "✅ fastlane配置创建完成"
      
      # 3. 运行fastlane构建
      - name: Run fastlane build
        script: |
          echo "=== 运行fastlane构建 ==="
          
          # 进入fastlane目录
          cd fastlane
          
          # 先尝试调试构建（更容易成功）
          echo "尝试调试构建..."
          fastlane ios debug_build || echo "调试构建失败，继续..."
          
          # 运行发布构建
          echo "运行发布构建..."
          fastlane ios release
          
          # 返回项目根目录
          cd ..
          
          echo "✅ fastlane构建完成"
      
      # 4. 验证构建产物
      - name: Verify artifacts
        script: |
          echo "=== 验证构建产物 ==="
          
          # 查找所有IPA文件
          echo "搜索IPA文件..."
          find . -name "*.ipa" -type f 2>/dev/null | while read ipa; do
            echo "找到IPA: $ipa"
            ls -la "$ipa"
          done
          
          # 检查预期的IPA
          EXPECTED_IPA="build/$XCODE_SCHEME.ipa"
          if [ -f "$EXPECTED_IPA" ]; then
            echo "✅ 找到预期的IPA: $EXPECTED_IPA"
            echo "文件大小: $(du -h "$EXPECTED_IPA" | cut -f1)"
            
            # 验证签名
            echo "验证IPA签名..."
            codesign -d -vvv "$EXPECTED_IPA" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier" || echo "无法验证签名详情"
          else
            echo "❌ 未找到预期的IPA: $EXPECTED_IPA"
            echo "build目录内容:"
            ls -la build/ 2>/dev/null || echo "build目录不存在"
            
            # 尝试查找任何IPA
            ANY_IPA=$(find . -name "*.ipa" -type f | head -1)
            if [ -n "$ANY_IPA" ]; then
              echo "⚠️ 找到其他位置的IPA: $ANY_IPA"
              echo "复制到build目录..."
              mkdir -p build
              cp "$ANY_IPA" "$EXPECTED_IPA"
              echo "✅ 已复制到: $EXPECTED_IPA"
            else
              echo "❌ 未找到任何IPA文件"
              exit 1
            fi
          fi
      
      # 5. 显示构建摘要
      - name: Build summary
        script: |
          echo "=== 构建摘要 ==="
          echo "✅ 构建成功!"
          echo ""
          echo "生成的产物:"
          echo "IPA: build/$XCODE_SCHEME.ipa"
          echo ""
          echo "文件大小:"
          du -h "build/$XCODE_SCHEME.ipa" 2>/dev/null || echo "IPA文件不存在"
          echo ""
          echo "构建完成时间: $(date)"
    
    artifacts:
      - build/*.ipa
      - fastlane/Appfile
      - fastlane/Fastfile
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "717@stlnd.net"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
