workflows:
  ios-simple:
    name: iOS Simple Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.test.ios.attaf"
      
      # 自动签名配置
      ios_signing:
        distribution_type: app_store  # development, ad_hoc, 或 app_store
        bundle_identifier: $BUNDLE_ID
        # 不需要 certificate_type，Codemagic 会自动处理
    
    scripts:
      - name: 安装依赖
        script: |
          if [ -f "Podfile" ]; then
            pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          else
            echo "未找到Podfile，跳过pod install"
          fi
      
      - name: 构建和导出
        script: |
          # 使用Codemagic提供的简化构建命令
          xcode-project build-ios \
            --workspace "$(find . -name '*.xcworkspace' -type d | head -1)" \
            --scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[0]')" \
            --export-options-plist-config '{"method": "app-store"}'
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
