workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      groups:
        - appstore_connect
      vars:
        # 基础配置
        APP_IDENTIFIER: "com.test.ios.attaf"
        APPLE_ID: "lingya00130@gmail.com"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      cancel_previous_builds: false
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    
    scripts:
      # 1. 设置环境和显示项目签名配置
      - name: Setup and show signing configuration
        script: |
          echo "=== 设置和显示签名配置 ==="
          echo "当前目录: $(pwd)"
          echo "Scheme: $XCODE_SCHEME"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $APP_IDENTIFIER"
          
          # 显示项目结构
          echo "项目结构:"
          ls -la
          
          # 显示项目的代码签名配置
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "项目文件中的签名配置:"
            echo "1. CODE_SIGN_STYLE:"
            grep -n "CODE_SIGN_STYLE" 123.xcodeproj/project.pbxproj || echo "未找到CODE_SIGN_STYLE"
            echo ""
            echo "2. CODE_SIGN_IDENTITY:"
            grep -n "CODE_SIGN_IDENTITY" 123.xcodeproj/project.pbxproj || echo "未找到CODE_SIGN_IDENTITY"
            echo ""
            echo "3. DEVELOPMENT_TEAM:"
            grep -n "DEVELOPMENT_TEAM" 123.xcodeproj/project.pbxproj | head -5 || echo "未找到DEVELOPMENT_TEAM"
            echo ""
            echo "4. PROVISIONING_PROFILE:"
            grep -n "PROVISIONING_PROFILE" 123.xcodeproj/project.pbxproj || echo "未找到PROVISIONING_PROFILE"
          fi
          
          # 创建构建目录
          mkdir -p build
      
      # 2. 修复项目中的代码签名冲突
      - name: Fix code signing conflicts
        script: |
          echo "=== 修复代码签名冲突 ==="
          
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            echo "备份项目文件..."
            cp 123.xcodeproj/project.pbxproj 123.xcodeproj/project.pbxproj.backup
            
            # 移除所有CODE_SIGN_IDENTITY设置（解决冲突）
            echo "移除CODE_SIGN_IDENTITY设置..."
            sed -i '' '/CODE_SIGN_IDENTITY/d' 123.xcodeproj/project.pbxproj
            
            # 确保CODE_SIGN_STYLE设置为Automatic
            echo "设置CODE_SIGN_STYLE为Automatic..."
            sed -i '' 's/CODE_SIGN_STYLE = [^;]*;/CODE_SIGN_STYLE = Automatic;/g' 123.xcodeproj/project.pbxproj
            
            # 如果项目中没有CODE_SIGN_STYLE，添加它
            if ! grep -q "CODE_SIGN_STYLE = Automatic" 123.xcodeproj/project.pbxproj; then
              echo "添加CODE_SIGN_STYLE设置..."
              # 在合适的位置添加CODE_SIGN_STYLE
              sed -i '' '/Begin XCBuildConfiguration section/,/End XCBuildConfiguration section/ s/Release = {/Release = {\n\t\t\tCODE_SIGN_STYLE = Automatic;/' 123.xcodeproj/project.pbxproj
              sed -i '' '/Begin XCBuildConfiguration section/,/End XCBuildConfiguration section/ s/Debug = {/Debug = {\n\t\t\tCODE_SIGN_STYLE = Automatic;/' 123.xcodeproj/project.pbxproj
            fi
            
            # 确保有正确的开发团队
            echo "设置开发团队为: $TEAM_ID"
            sed -i '' "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = $TEAM_ID;/g" 123.xcodeproj/project.pbxproj
            
            # 确保有正确的bundle identifier
            echo "设置bundle identifier为: $APP_IDENTIFIER"
            sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $APP_IDENTIFIER;/g" 123.xcodeproj/project.pbxproj
            
            # 移除所有provisioning profile设置（让自动签名处理）
            echo "移除所有provisioning profile设置..."
            sed -i '' '/PROVISIONING_PROFILE/d' 123.xcodeproj/project.pbxproj
            sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' 123.xcodeproj/project.pbxproj
            
            echo "✅ 代码签名冲突已修复"
            echo "修复后的配置:"
            echo "CODE_SIGN_STYLE:"
            grep -n "CODE_SIGN_STYLE" 123.xcodeproj/project.pbxproj || echo "未找到"
            echo "CODE_SIGN_IDENTITY:"
            grep -n "CODE_SIGN_IDENTITY" 123.xcodeproj/project.pbxproj || echo "已移除"
          else
            echo "⚠️ 未找到项目配置文件，跳过修复"
          fi
      
      # 3. 使用完全自动签名构建
      - name: Build with clean automatic signing
        script: |
          echo "=== 使用完全自动签名构建 ==="
          
          # 清理之前的构建
          rm -rf build/*.xcarchive
          
          # 显示当前可用的证书
          echo "可用证书:"
          security find-identity -p codesigning -v | grep -i "apple" || true
          
          # 显示当前可用的配置文件
          echo "可用配置文件:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -5 || echo "无配置文件"
          
          # 使用xcodebuild的clean命令
          echo "清理项目..."
          if [ -d "123.xcworkspace" ]; then
            xcodebuild clean -workspace "123.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Release 2>&1 | tail -10 || true
          elif [ -d "123.xcodeproj" ]; then
            xcodebuild clean -project "123.xcodeproj" -scheme "$XCODE_SCHEME" -configuration Release 2>&1 | tail -10 || true
          fi
          
          # 构建archive，不指定任何签名参数（让项目配置决定）
          echo "构建archive..."
          if [ -d "123.xcworkspace" ]; then
            echo "使用workspace构建..."
            
            xcodebuild archive \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              2>&1 | tee build/archive.log
            
          elif [ -d "123.xcodeproj" ]; then
            echo "使用project构建..."
            
            xcodebuild archive \
              -project "123.xcodeproj" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -destination 'generic/platform=iOS' \
              -allowProvisioningUpdates \
              2>&1 | tee build/archive.log
          fi
          
          # 检查archive是否成功
          if [ -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "✅ archive构建成功"
            
            # 显示archive中的签名信息
            echo "Archive签名信息:"
            codesign -d -vvv "build/$XCODE_SCHEME.xcarchive/Products/Applications/$XCODE_SCHEME.app" 2>&1 | head -20 || echo "无法获取签名信息"
          else
            echo "❌ archive构建失败"
            echo "查看日志:"
            tail -50 build/archive.log
            exit 1
          fi
      
      # 4. 导出IPA（使用手动指定profile）
      - name: Export IPA with specific profile
        script: |
          echo "=== 导出IPA ==="
          
          # 清理之前的IPA
          rm -rf build/*.ipa
          
          # 创建export_options.plist，明确指定使用codemagic_Production
          cat > build/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_IDENTIFIER</key>
                  <string>codemagic_Production</string>
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF
          
          echo "export_options.plist内容:"
          cat build/export_options.plist
          
          # 执行导出
          echo "开始导出IPA..."
          xcodebuild -exportArchive \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist "build/export_options.plist" \
            -exportPath "build" \
            -allowProvisioningUpdates \
            2>&1 | tee build/export.log
          
          echo "✅ 导出完成"
      
      # 5. 验证和重命名IPA文件
      - name: Verify and rename IPA
        script: |
          echo "=== 验证和重命名IPA文件 ==="
          
          # 查找生成的IPA文件
          echo "查找IPA文件..."
          IPA_FILES=$(find build -name "*.ipa" 2>/dev/null)
          
          if [ -z "$IPA_FILES" ]; then
            echo "❌ 未找到IPA文件"
            echo "导出日志最后50行:"
            tail -50 build/export.log || echo "无导出日志"
            exit 1
          fi
          
          echo "找到的IPA文件:"
          echo "$IPA_FILES"
          
          # 如果IPA文件不在根目录，移动到根目录
          if [ ! -f "build/$XCODE_SCHEME.ipa" ]; then
            FIRST_IPA=$(echo "$IPA_FILES" | head -1)
            echo "将IPA文件复制到标准位置: $FIRST_IPA -> build/$XCODE_SCHEME.ipa"
            cp "$FIRST_IPA" "build/$XCODE_SCHEME.ipa"
          fi
          
          # 验证IPA文件
          if [ -f "build/$XCODE_SCHEME.ipa" ]; then
            echo "✅ IPA文件创建成功: build/$XCODE_SCHEME.ipa"
            echo "文件大小: $(du -h "build/$XCODE_SCHEME.ipa" | cut -f1)"
            
            # 验证签名
            echo "验证IPA签名..."
            codesign -d -vvv "build/$XCODE_SCHEME.ipa" 2>&1 | head -10 || echo "无法验证IPA签名"
          else
            echo "❌ IPA文件未创建"
            exit 1
          fi
      
      # 6. 显示构建摘要
      - name: Build summary
        script: |
          echo "=== 构建摘要 ==="
          echo "✅ 构建成功!"
          echo ""
          echo "生成的产物:"
          echo "IPA: build/$XCODE_SCHEME.ipa"
          echo "Archive: build/$XCODE_SCHEME.xcarchive"
          echo ""
          echo "文件大小:"
          du -h "build/$XCODE_SCHEME.ipa" 2>/dev/null || echo "IPA文件不存在"
          du -h "build/$XCODE_SCHEME.xcarchive" 2>/dev/null || echo "Archive不存在"
    
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
      - build/export_options.plist
      - build/archive.log
      - build/export.log
    
    publishing:
      # 邮件通知
      email:
        recipients:
          - "lingya00130@gmail.com"
        notify:
          success: true
          failure: true
      
      # 发布到App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testers"
