# 简化版本
workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      groups:
        - appstore_signing
      vars:
        SCHEME: "123"
        TEAM_ID: "7994453ZHZ"
        BUNDLE_ID: "com.test.ios.attaf"
        PROVISIONING_PROFILE_NAME: "codemagic Production"
    
    scripts:
      - name: Build iOS app
        script: |
          # 简单构建命令
          xcodebuild archive \
            -workspace "123.xcworkspace" \
            -scheme "123" \
            -configuration Release \
            -archivePath "build/123.xcarchive" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE="Manual"
          
          # 导出
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROVISIONING_PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath "build/123.xcarchive" \
            -exportPath "build" \
            -exportOptionsPlist "exportOptions.plist"
    
    artifacts:
      - build/*.ipa
