workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: Build iOS
        script: |
          # 最简单的构建
          sudo gem install fastlane -NV
          
          mkdir -p fastlane
          cat > fastlane/Fastfile << 'EOF'
          lane :build do
            gym(
              workspace: "123.xcworkspace",
              scheme: "123",
              export_method: "app-store",
              output_directory: "build"
            )
          end
          EOF
          
          cd fastlane
          fastlane ios build
    
    artifacts:
      - build/*.ipa
