workflows:
  ios-fastlane-simple:
    name: iOS Fastlane Simple
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: Build with fastlane
        script: |
          # 安装 fastlane
          sudo gem install fastlane -NV
          
          # 直接运行 fastlane 命令
          fastlane run gym \
            workspace:"123.xcworkspace" \
            scheme:"123" \
            clean:true \
            output_directory:"build" \
            export_method:"app-store" \
            silent:true \
            skip_package_ipa:false
          
          # 检查结果
          if [ -f "build/*.ipa" ]; then
            echo "✅ Build successful"
          else
            echo "Checking for IPA..."
            find . -name "*.ipa" -type f
          fi
