workflows:
  ios-simple-fastlane:
    name: iOS Simple Fastlane
    environment:
      xcode: latest
      groups:
        - appstore_signing
    
    scripts:
      - name: One-step fastlane build
        script: |
          # 最简单的方法：直接使用 fastlane gym
          sudo gem install fastlane -NV
          
          # 直接调用 gym，不创建 Fastfile
          fastlane run gym \
            workspace:"123.xcworkspace" \
            scheme:"123" \
            export_method:"app-store" \
            output_directory:"build" \
            clean:true
          
          echo "Build attempt completed"
          ls build/*.ipa 2>/dev/null || echo "Checking for IPA..."
      
      - name: Fallback if needed
        script: |
          # 如果上面失败，尝试这个
          if [ ! -f "build/*.ipa" ]; then
            echo "Trying alternative approach..."
            
            # 使用 xcodebuild 但让 fastlane 处理签名
            fastlane run build_ios_app \
              workspace:"123.xcworkspace" \
              scheme:"123" \
              export_method:"app-store"
          fi
          
          # 最终检查
          find . -name "*.ipa" -type f | xargs ls -lh 2>/dev/null || echo "No IPA files"
    
    artifacts:
      - build/*.ipa
