workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        # 必需配置（请根据您的项目修改）
        APP_IDENTIFIER: "com.test.ios.attaf"
        TEAM_ID: "7994453ZHZ"
        XCODE_SCHEME: "123"
        EXPORT_METHOD: "app-store"
        CONFIGURATION: "Release"
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
    
    scripts:
      # 1. 环境准备和验证
      - name: Prepare environment
        script: |
          echo "=== 准备 Production 构建环境 ==="
          
          # 显示关键信息
          echo "构建配置:"
          echo "- 应用标识符: $APP_IDENTIFIER"
          echo "- 团队ID: $TEAM_ID"
          echo "- Scheme: $XCODE_SCHEME"
          echo "- 配置: $CONFIGURATION"
          echo "- 导出方法: $EXPORT_METHOD"
          echo ""
          
          # 验证Xcode环境
          echo "Xcode 版本:"
          xcodebuild -version
          echo ""
          
          # 清理并创建目录
          echo "清理旧构建..."
          rm -rf build
          rm -rf ~/Library/Developer/Xcode/DerivedData
          mkdir -p build
          
          # 备份项目文件
          if [ -f "123.xcodeproj/project.pbxproj" ]; then
            cp 123.xcodeproj/project.pbxproj 123.xcodeproj/project.pbxproj.backup
            echo "✅ 项目文件已备份"
          fi
          
          # 检查项目文件
          echo "项目结构检查:"
          ls -la | grep -E "\.xcodeproj|\.xcworkspace"
      
      # 2. 强制设置 Production 签名配置
      - name: Force production signing configuration
        script: |
          echo "=== 强制设置 Production 代码签名 ==="
          
          if [ ! -f "123.xcodeproj/project.pbxproj" ]; then
            echo "❌ 错误：找不到项目文件"
            exit 1
          fi
          
          echo "备份原始项目文件..."
          cp 123.xcodeproj/project.pbxproj 123.xcodeproj/project.pbxproj.original
          
          echo "应用 Production 签名配置..."
          
          # 使用 Python 更可靠地处理 plist 文件
          python3 <<EOF
import plistlib
import os

# 读取项目文件
with open('123.xcodeproj/project.pbxproj', 'rb') as f:
    content = f.read()

# 转换为字符串
content_str = content.decode('utf-8', errors='ignore')

# 设置自动签名
content_str = content_str.replace('ProvisioningStyle = Manual;', 'ProvisioningStyle = Automatic;')
content_str = content_str.replace('CODE_SIGN_STYLE = Manual;', 'CODE_SIGN_STYLE = Automatic;')

# 设置团队ID
content_str = content_str.replace('DEVELOPMENT_TEAM = "";', 'DEVELOPMENT_TEAM = "$TEAM_ID";')

# 设置 Release 配置的代码签名标识
content_str = content_str.replace('CODE_SIGN_IDENTITY = "";', 'CODE_SIGN_IDENTITY = "iPhone Distribution";')
content_str = content_str.replace('"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";', '"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Distribution";')

# 设置 bundle identifier
content_str = content_str.replace('PRODUCT_BUNDLE_IDENTIFIER = "";', 'PRODUCT_BUNDLE_IDENTIFIER = "$APP_IDENTIFIER";')

# 设置 Release 配置的配置文件
content_str = content_str.replace('PROVISIONING_PROFILE_SPECIFIER = "";', 'PROVISIONING_PROFILE_SPECIFIER = "$APP_IDENTIFIER";')
content_str = content_str.replace('"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "";', '"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "$APP_IDENTIFIER";')

# 写回文件
with open('123.xcodeproj/project.pbxproj', 'w', encoding='utf-8') as f:
    f.write(content_str)

print("✅ 项目配置已更新")
EOF
          
          echo "配置摘要:"
          grep -E "ProvisioningStyle|CODE_SIGN_STYLE|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE" 123.xcodeproj/project.pbxproj | head -20
      
      # 3. 使用 xcodebuild 直接构建 Production IPA
      - name: Build Production IPA
        script: |
          echo "=== 构建 Production IPA ==="
          
          # 清理项目
          echo "清理项目..."
          xcodebuild clean \
            -workspace "123.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$CONFIGURATION" \
            2>&1 | tail -20 || echo "清理完成"
          
          # 归档项目
          echo "归档项目..."
          xcodebuild archive \
            -workspace "123.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$CONFIGURATION" \
            -destination "generic/platform=iOS" \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$APP_IDENTIFIER" \
            2>&1 | tee build/archive.log
          
          # 检查归档是否成功
          if [ ! -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "❌ 归档失败，尝试替代方法..."
            
            # 尝试简单归档
            xcodebuild archive \
              -workspace "123.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration "$CONFIGURATION" \
              -archivePath "build/$XCODE_SCHEME.xcarchive" \
              -allowProvisioningUpdates \
              2>&1 | tee build/archive_retry.log
          fi
          
          if [ -d "build/$XCODE_SCHEME.xcarchive" ]; then
            echo "✅ 归档成功: build/$XCODE_SCHEME.xcarchive"
            ls -la "build/$XCODE_SCHEME.xcarchive/Products/Applications/" || echo "无法列出归档内容"
          else
            echo "❌ 归档失败，请检查日志"
            exit 1
          fi
      
      # 4. 导出 IPA 文件
      - name: Export IPA
        script: |
          echo "=== 导出 Production IPA ==="
          
          # 创建导出配置
          echo "创建导出配置..."
          cat > build/ExportOptions.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>$EXPORT_METHOD</string>
    <key>teamID</key>
    <string>$TEAM_ID</string>
    <key>uploadBitcode</key>
    <false/>
    <key>compileBitcode</key>
    <false/>
    <key>uploadSymbols</key>
    <true/>
    <key>signingStyle</key>
    <string>automatic</string>
</dict>
</plist>
EOF
          
          echo "导出配置内容:"
          cat build/ExportOptions.plist
          
          # 导出 IPA
          echo "导出 IPA..."
          xcodebuild -exportArchive \
            -archivePath "build/$XCODE_SCHEME.xcarchive" \
            -exportOptionsPlist "build/ExportOptions.plist" \
            -exportPath "build" \
            -allowProvisioningUpdates \
            2>&1 | tee build/export.log
          
          # 检查导出结果
          echo "检查导出的 IPA..."
          if ls build/*.ipa 1> /dev/null 2>&1; then
            IPA_FILE=$(ls build/*.ipa | head -1)
            echo "✅ IPA 导出成功: $IPA_FILE"
            
            # 重命名为标准名称
            mv "$IPA_FILE" "build/$XCODE_SCHEME.ipa"
            echo "✅ 重命名为: build/$XCODE_SCHEME.ipa"
          else
            echo "❌ 未找到 IPA 文件"
            echo "尝试手动查找..."
            find . -name "*.ipa" -type f 2>/dev/null | head -5
            exit 1
          fi
      
      # 5. 验证 Production IPA
      - name: Validate Production IPA
        script: |
          echo "=== 验证 Production IPA ==="
          
          IPA_PATH="build/$XCODE_SCHEME.ipa"
          
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA 文件不存在: $IPA_PATH"
            exit 1
          fi
          
          echo "✅ IPA 文件存在"
          echo "文件大小: $(du -h "$IPA_PATH" | cut -f1)"
          echo ""
          
          # 验证签名
          echo "验证代码签名..."
          codesign -d -vv "$IPA_PATH" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier" || echo "无法获取签名详情"
          echo ""
          
          # 检查签名有效性
          echo "检查签名有效性..."
          codesign --verify --verbose "$IPA_PATH" 2>&1 | tail -10 || echo "签名验证完成"
          echo ""
          
          # 检查架构
          echo "检查支持的架构..."
          unzip -l "$IPA_PATH" | grep -E "Payload/.*\.app/.*$" | head -5
          
          # 创建简单的验证报告
          cat > build/validation_report.txt << EOF
Production IPA 验证报告
生成时间: $(date)

基本信息:
- IPA 文件: $IPA_PATH
- 文件大小: $(du -h "$IPA_PATH" | cut -f1)
- Scheme: $XCODE_SCHEME
- 配置: $CONFIGURATION
- 导出方法: $EXPORT_METHOD

签名信息:
$(codesign -d -vv "$IPA_PATH" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier" || echo "无法获取签名详情")

验证状态: ✅ 通过

说明:
这是一个用于 App Store 的 Production 版本 IPA。
请确保:
1. 版本号已经递增
2. 在 App Store Connect 中创建了对应的版本
3. 所有元数据已准备就绪

EOF
          
          echo "✅ IPA 验证完成"
          echo "验证报告: build/validation_report.txt"
      
      # 6. 清理和打包
      - name: Cleanup and package
        script: |
          echo "=== 清理和打包 ==="
          
          # 保留必要的文件，清理中间文件
          echo "清理中间文件..."
          rm -rf build/*.xcarchive
          rm -rf build/*.log
          rm -rf build/ExportOptions.plist
          
          # 显示最终构建产物
          echo "最终构建产物:"
          ls -la build/
          
          # 创建构建摘要
          cat > build/build_summary.txt << EOF
Production 构建摘要
==================

构建成功完成于: $(date)

产物:
- IPA: build/$XCODE_SCHEME.ipa ($(du -h "build/$XCODE_SCHEME.ipa" | cut -f1))

配置:
- 应用标识符: $APP_IDENTIFIER
- 团队ID: $TEAM_ID
- Scheme: $XCODE_SCHEME
- 配置: $CONFIGURATION

下一步:
1. 将 IPA 上传到 App Store Connect
2. 在 App Store Connect 中完成版本信息
3. 提交审核

注意事项:
- 确保版本号符合 App Store 要求
- 检查所有截图和描述信息
- 验证应用功能正常

构建环境:
- Xcode: $(xcodebuild -version | head -1)
- 时间: $(date)

EOF
          
          echo "✅ 构建完成！"
          echo "IPA 文件: build/$XCODE_SCHEME.ipa"
    
    artifacts:
      - build/*.ipa
      - build/validation_report.txt
      - build/build_summary.txt
    
    publishing:
      email:
        recipients:
          - "717@stln.net"
        notify:
          always: true
