workflows:
  ios-simple:
    name: iOS Simple Build
    environment:
      xcode: latest
    
    scripts:
      - name: Just test build
        script: |
          # 先测试能否构建（不签名）
          xcodebuild build \
            -workspace "123.xcworkspace" \
            -scheme "123" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO
          
          echo "If this works, the project structure is OK"
          echo "The issue is with code signing configuration"
