workflows:
  check-current:
    name: Check Current Settings
    environment:
      xcode: latest
    
    scripts:
      - name: Show all env vars
        script: |
          echo "=== Current environment variables ==="
          echo "Groups defined in YAML: appstore_signing"
          echo ""
          echo "Looking for APPSTORE variables..."
          if [ -z "$APPSTORE_CERTIFICATE_URL" ]; then
            echo "❌ APPSTORE_CERTIFICATE_URL: NOT SET"
          else
            echo "✅ APPSTORE_CERTIFICATE_URL: SET (length: ${#APPSTORE_CERTIFICATE_URL})"
          fi
          
          if [ -z "$APPSTORE_PROVISIONING_PROFILE_URL" ]; then
            echo "❌ APPSTORE_PROVISIONING_PROFILE_URL: NOT SET"
          else
            echo "✅ APPSTORE_PROVISIONING_PROFILE_URL: SET (length: ${#APPSTORE_PROVISIONING_PROFILE_URL})"
          fi
          
          if [ -z "$APPSTORE_CERTIFICATE_PASSWORD" ]; then
            echo "❌ APPSTORE_CERTIFICATE_PASSWORD: NOT SET"
          else
            echo "✅ APPSTORE_CERTIFICATE_PASSWORD: SET (length: ${#APPSTORE_CERTIFICATE_PASSWORD})"
          fi
          
          echo ""
          echo "如果没有设置，请按照上述步骤在 Codemagic UI 中设置。"
